abaplint/abaplint

- package.json
> chore(package): update uglify-js to version 3.0.23

- package.json
Closes #197
not tested, will roll back if it breaks
> chore(package): update browserify to version 15.2.0

- .gitignore
- src/abap/pretty_printer.ts
- src/rules/indentation.ts
- test/abap/pretty_printer.ts
to #337 
P.S. I'd apply `createRunner` to all the test in the file, would you mind ?
P.P.S. what is your TS flow ? straight forward approach seems to be very bulky: run `tsc -w` in one console, run `mocha --watch` in another ... and running debugger is pain ... maybe I need to read a couple of articles on how to develop for ts ;)
> alightTryCatch indent rule option

- docs/index.md
- src/abap/pretty_printer.ts
- src/rules/indentation.ts
- test/abap/pretty_printer.ts
> Class indent rebase

- src/abap/statements/insert_report.ts
- test/abap/statements/insert_report.ts
> add FIXED-POINT ARITHMETIC to INSERT REPORT

- src/objects/maintenance_and_transport_object.ts
> Adjust AREA regex for reserved namespaces

- package.json
- scripts/schema.js
- src/config.ts
- test/config.ts
> boolean form of rules

- src/rules/short_case.ts
- src/rules/whitespace/sequential_blank.ts
> Fix off by one errors in descriptions

- package-lock.json
- package.json
- src/objects/_abstract_object.ts
- src/objects/_iobject.ts
- src/rules/index.ts
- src/rules/release_idoc.ts
- test/rules/release_idoc.ts
new rule release_idoc, closes #455
> new rule release_idoc, closes #455

- web/playground/src/index.ts
- web/playground/src/monaco/AbapSnippetProvider.ts
- web/playground/tsconfig.json
More or less the same as https://marketplace.visualstudio.com/items?itemName=frehu.abap-snippets
(I will actually have to do a plugin update to address some minor issues which are fixed here)
> Add snippets based on abap snippets plugin

- src/rules/_naming_rule_config.ts
> Correct inheritance for NamingRuleConfig

- src/rules/method_length.ts
- test/rules/method_length.ts
> Rule method_length: Add Check for Empty Method

- src/abap/types/interface_definition.ts
- src/rules/abapdoc.ts
- test/rules/abapdoc.ts
> Rule: Abapdoc - Setting for Local Classes/Interfaces

- .github/workflows/coverage.yml
- .github/workflows/main.yml
- .github/workflows/playground.yml
Github actions not triggered for PR, closes #608
> Github actions not triggered for PR

- src/abap/statements/move.ts
- test/abap/statements/move.ts
Add concat operator from #626 .
> Add new concat operator

- src/pretty_printer/fix_keyword_case.ts
- src/pretty_printer/pretty_printer.ts
- test/abap/pretty_printer.ts
> Pretty-printer: lowercase non-keywords

- src/rules/fully_type_constants.ts
- test/rules/fully_type_constants.ts
> Rule fully_type_constants, data defined as table

- .github/workflows/coverage.yml
- .github/workflows/main.yml
- .github/workflows/playground.yml
- travis.sh
* renaming
* playground deploy moved from travis script to github actions
> CI: Github Actions changes

- .github/workflows/autotag-new-versions.yml
potentially may need the first tag to be created manually ... but maybe will work
triggered only on `package.json` change
> auto tag workflow

- .github/workflows/autotag-new-versions.yml
> fix github.repository

- src/abap/types/class_definition.ts
- src/rules/abapdoc.ts
- test/rules/abapdoc.ts
I have run tests by 'npm test' and the result is '3327 passing'. 
Please help to review.
closes #719
> ABAP doc for method redefinitions

- src/abap/expressions/string_template.ts
> StringTemplate: add more formatting options

- scripts/schema.json
- src/cli/apack_dependency_provider.ts
- src/cli/cli.ts
- src/config.ts
- test/cli/apack_dependency_provider.ts
Resolves #491 
- Looks for the apack manifest and adds its dependencies to the list of cloned repos.
> Add apack support

- src/abap/expressions/string_template_formatting.ts
- test/abap/statements/move.ts
adds the rest of the formatting options, closes #765 
(its probably not 100% correct, but can fix when reports arise)
> String Templates: Formatting options

- src/abap/types/form_definition.ts
- test/rules/identical_form_names.ts
fix #793 (granted, it's a bit of a hack)
> identical_form_names: false positive, dash

- packages/core/scripts/schema.json
- packages/core/src/rules/naming/object_naming.ts
- packages/core/test/rules/naming/object_naming.ts
also:
- fixed some typos in the other tests
- removed unused method
closes #811
> Object Naming: Add SSFO+SSST (Smartforms/Smartstyles)

- packages/core/src/abap/2_statements/expressions/string_template_formatting.ts
- packages/core/test/abap/statements/move.ts
> String Templates: allow Source for DECIMAL formatting

- packages/core/src/abap/2_statements/expressions/string_template_formatting.ts
- packages/core/test/abap/statements/move.ts
> string templates: change pad/align/width logic

- packages/core/src/rules/line_length.ts
- packages/core/test/rules/line_length.ts
resolves #800 
also refactored for legibility, can revert if requested
> line_length: add maximum line length + refactor

- packages/core/scripts/schema.json
- packages/core/src/rules/keyword_case.ts
- packages/core/test/rules/keyword_case.ts
closes #745
Add option: list of keywords to ignore. Also affects pretty printer
> keyword_case: add option, list of keywords to ignore

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/5_syntax/_current_scope.ts
- packages/core/src/abap/5_syntax/_spaghetti_scope.ts
- packages/core/src/abap/5_syntax/global_definitions/find_global_definitions.ts
- packages/core/src/abap/5_syntax/syntax.ts
- packages/core/src/abap/5_syntax/syntax_result.ts
- packages/core/src/abap/types/_class_attributes.ts
- packages/core/src/abap/types/_interface_definition.ts
- packages/core/src/abap/types/class_attributes.ts
- packages/core/src/abap/types/interface_definition.ts
- packages/core/src/objects/class.ts
- packages/core/src/objects/interface.ts
- packages/core/src/registry.ts
- packages/core/test/rules/syntax/unknown_types.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
* cache global clas and intf definitions
> 2.32.26, additional typing

- packages/core/src/rules/whitespace/double_space.ts
- packages/core/test/rules/whitespace/double_space.ts
> double_space: add quick fix

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/cli/src/cli.ts
- packages/cli/src/fixes.ts
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/edit_helper.ts
- packages/core/src/index.ts
- packages/core/src/rules/use_new.ts
- packages/core/test/edit_helper.ts
- packages/core/test/rules/_utils.ts
- packages/core/test/rules/use_new.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.34.1, bugfixes: quickfix use_new, cli --fix

- packages/core/src/edit_helper.ts
- packages/core/src/rules/keyword_case.ts
- packages/core/src/rules/start_at_tab.ts
- packages/core/test/edit_helper.ts
- packages/core/test/rules/_utils.ts
- packages/core/test/rules/line_break_multiple_parameters.ts
> bugfix multiple edits, same line

- packages/core/scripts/schema.json
- packages/core/src/rules/class_attribute_names.ts
- packages/core/test/rules/class_attribute_names.ts
closes #880 
interface check is enabled by default
> class_attribute_names: add check for interfaces, add option to ignore

- packages/core/src/rules/contains_tab.ts
- packages/core/test/rules/contains_tab.ts
> contains_tab: reported position to range of sequential tabs, add fix

- packages/core/scripts/schema.json
- packages/core/src/rules/line_only_punc.ts
- packages/core/test/rules/line_only_punc.ts
> line_only_punc: add quick fix

- packages/core/src/objects/lock_object.ts
not sure if this is release dependent
> Lock objects support namespaces

- packages/core/src/objects/mime_object.ts
Key for SMIME is a GUID, data element SDOK_LOID C(32)
> Adjust max length for SMIME objects

- packages/core/src/abap/2_statements/statements/selectionscreen.ts
- packages/core/test/abap/syntax/basic_variables.ts
- packages/core/test/rules/check_text_elements.ts
Works like SELECTION-SCREEN COMMENT
Closes https://github.com/abaplint/abaplint/issues/885
> Pushbutton to accept text element or variable

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/scripts/schema.json
- packages/core/src/abap/2_statements/statements/import.ts
- packages/core/src/abap/4_file_information/_abap_file_information.ts
- packages/core/src/abap/5_syntax/_inline.ts
- packages/core/src/abap/5_syntax/expressions/source.ts
- packages/core/src/abap/5_syntax/statements/assign.ts
- packages/core/src/abap/5_syntax/statements/convert.ts
- packages/core/src/abap/5_syntax/statements/describe.ts
- packages/core/src/abap/5_syntax/statements/find.ts
- packages/core/src/abap/5_syntax/statements/get_parameter.ts
- packages/core/src/abap/5_syntax/statements/get_time.ts
- packages/core/src/abap/5_syntax/statements/message.ts
- packages/core/src/abap/5_syntax/syntax.ts
- packages/core/src/rules/sicf_consistency.ts
- packages/core/test/abap/statements/export.ts
- packages/core/test/abap/statements/import.ts
- packages/core/test/abap/syntax/basic_variables.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.36.12, SICF consistency, additional typing

- packages/core/src/ddic.ts
https://help.sap.com/doc/abapdocu_754_index_htm/7.54/en-US/abenddic_builtin_types.htm
> Add missing data types

- packages/cli/README.md
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/cli/src/cli.ts
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/_iregistry.ts
- packages/core/src/config.ts
- packages/core/src/registry.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
* do not count dependencies towards total progress when finding issues
* output parsing performance, closes https://github.com/abaplint/abaplint/issues/959
> 2.37.8, fix progress indication, skip deps

- packages/cli/README.md
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/cli/src/cli.ts
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/_iregistry.ts
- packages/core/src/abap/nodes/statement_node.ts
- packages/core/src/registry.ts
- packages/core/src/rules/check_include.ts
- packages/core/src/rules/check_text_elements.ts
- packages/core/src/rules/commented_code.ts
- packages/core/src/rules/exporting.ts
- packages/core/src/rules/functional_writing.ts
- packages/core/src/rules/obsolete_statement.ts
- packages/core/test/rules/commented_code.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.37.9, rule performance

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/5_syntax/expressions/component_name.ts
- packages/core/src/abap/5_syntax/expressions/field_chain.ts
- packages/core/src/abap/5_syntax/expressions/target.ts
- packages/core/src/ddic.ts
- packages/core/src/objects/table.ts
- packages/core/test/objects/table.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.37.11, TABL fixes

- packages/cli/src/formatters/standard.ts
> add helper vars for easier sort, add sort by row/col

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/5_syntax/expressions/select.ts
- packages/core/test/abap/syntax/syntax.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.38.20, SELECT, FAE bugfix

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/5_syntax/_builtin.ts
- packages/core/src/abap/5_syntax/basic_types.ts
- packages/core/src/abap/5_syntax/global_definitions/find_global_definitions.ts
- packages/core/test/abap/syntax/syntax.ts
- packages/core/test/rules/method_length.ts
- packages/core/test/rules/unknown_types.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
- web/playground/tsconfig.json
> 2.39.13, bugfixes

- packages/core/scripts/schema.json
- packages/core/src/rules/obsolete_statement.ts
- packages/core/test/rules/obsolete_statement.ts
resolves #1233 
additionally:
- buffer statement to reduce method calls
- rename `sta` to `staNode` so its more clear what variable is what
> obsolete_statement: Add FIELD-SYMBOL ... STRUCTURE

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/files/_abstract_file.ts
- packages/core/test/registry.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.39.28, handle filename encoding

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/objects/_abap_object.ts
- packages/core/src/objects/_abstract_object.ts
- packages/core/src/rules/allowed_object_naming.ts
- packages/core/test/rules/allowed_object_naming.ts
- packages/core/test/rules/check_include.ts
- packages/core/test/rules/message_exists.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.39.29, find the correct files

- .github/regression/run.js
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/1_lexer/lexer.ts
- packages/core/src/abap/2_statements/expand_macros.ts
- packages/core/src/abap/2_statements/statement_parser.ts
- packages/core/src/index.ts
- packages/core/src/position.ts
- packages/core/src/rules/downport.ts
- packages/core/src/rules/indentation.ts
- packages/core/src/rules/keyword_case.ts
- packages/core/src/rules/max_one_statement.ts
- packages/core/test/abap/ast.ts
- packages/core/test/abap/macros.ts
- packages/core/test/abap/syntax/syntax.ts
- packages/core/test/rules/indentation.ts
- packages/core/test/rules/keyword_case.ts
- packages/core/test/rules/max_one_statement.ts
- packages/core/test/rules/parser_error.ts
- packages/core/test/stats/method_length_stats.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.42.0, expanding macros

- packages/core/scripts/schema.json
- packages/core/src/_config.ts
- packages/core/src/registry.ts
- packages/core/test/registry.ts
> Add global exclude mechanism

- packages/core/scripts/schema.json
- packages/core/src/lsp/diagnostics.ts
- packages/core/src/severity.ts
- packages/core/test/severity.ts
> Fix severity values

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/cli/src/cli.ts
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/2_statements/expressions/exception_name.ts
- packages/core/src/abap/2_statements/expressions/index.ts
- packages/core/src/abap/2_statements/expressions/method_source.ts
- packages/core/src/abap/2_statements/statements/message.ts
- packages/core/src/rules/check_subrc.ts
- packages/core/src/rules/prefer_is_not.ts
- packages/core/test/abap/statements/call.ts
- packages/core/test/abap/statements/message.ts
- packages/core/test/rules/check_subrc.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
closes https://github.com/abaplint/abaplint/issues/1351
> 2.48.1, bugfixes

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/objects/idoc.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.48.2, allow namespaces for IDOC

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/2_statements/expressions/sql_field_name.ts
- packages/core/test/abap/statements/select.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.48.3, namespace in sql field name

- packages/core/scripts/schema.json
- packages/core/scripts/schema.ts
- packages/core/src/rules/index.ts
- packages/core/src/rules/method_overwrites_builtin.ts
- packages/core/test/rules/method_overwrites_builtin.ts
> New rule: method_overwrites_builtin

- packages/core/src/rules/obsolete_statement.ts
> full command for obsolete statement TYPE-POOLS

- packages/core/scripts/schema.json
- packages/core/scripts/schema.ts
- packages/core/src/rules/function_module_recommendations.ts
- packages/core/src/rules/index.ts
- packages/core/test/rules/function_module_recommendations.ts
> New rule: FM recommendations

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/scripts/schema.json
- packages/core/src/rules/keyword_case.ts
- packages/core/test/rules/keyword_case.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.58.5, keyword_case quick fix

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/scripts/schema.json
- packages/core/src/rules/definitions_top.ts
- packages/core/test/rules/definitions_top.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.58.12, definitions_top, quick fix

- .github/regression/run.js
- .github/workflows/regression.yml
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/2_statements/expressions/source.ts
- packages/core/src/abap/5_syntax/expressions/source.ts
- packages/core/test/abap/syntax/syntax.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.58.13, syntax check bugfix

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/2_statements/expressions/attribute_chain.ts
- packages/core/src/abap/2_statements/expressions/index.ts
- packages/core/src/abap/2_statements/expressions/source.ts
- packages/core/test/abap/statements/move.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.58.19, add new attribute chain expression

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/scripts/schema.json
- packages/core/src/abap/2_statements/statements/fieldsymbol.ts
- packages/core/src/rules/definitions_top.ts
- packages/core/test/abap/statements/fieldsymbol.ts
- packages/core/test/rules/definitions_top.ts
- packages/core/test/rules/local_variable_names.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
it will no longer suggest quick fixes for structured definitions
#1505
> 2.58.21, refactor definitions_top rule

- .github/workflows/regression.yml
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/5_syntax/basic_types.ts
- packages/core/src/abap/5_syntax/structures/types.ts
- packages/core/src/abap/types/_typed_identifier.ts
- packages/core/src/rules/downport.ts
- packages/core/test/rules/downport.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
* Fix undefined error
* Keep code after NEW, if exists
* Qualified names for outlining of TYPES
> 2.58.23, downport, bugfixes

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/2_statements/statements/loop.ts
- packages/core/src/abap/5_syntax/basic_types.ts
- packages/core/src/abap/5_syntax/expressions/source.ts
- packages/core/src/abap/types/basic/_abstract_type.ts
- packages/core/src/abap/types/basic/table_type.ts
- packages/core/src/lsp/_lookup.ts
- packages/core/src/rules/downport.ts
- packages/core/test/lsp/hover.ts
- packages/core/test/rules/downport.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
* downport, outline LOOP AT
* Infer type for APPEND VALUE #
> 2.58.24, downport, outline LOOP AT

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/5_syntax/expressions/new_object.ts
- packages/core/src/abap/5_syntax/expressions/type_table.ts
- packages/core/test/lsp/hover.ts
- packages/core/test/rules/unused_variables.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
* bugfix, qualified name for table types in interfaces
* unused_variables, fix false positive
> 2.58.26, unused_variables, fix false positive

- package-lock.json
- package.json
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/scripts/schema.json
- packages/core/src/abap/2_statements/expressions/for.ts
- packages/core/src/abap/2_statements/expressions/macro_name.ts
- packages/core/src/abap/2_statements/expressions/sql_field_list.ts
- packages/core/src/issue.ts
- packages/core/src/rules/unused_methods.ts
- packages/core/test/abap/statements/define.ts
- packages/core/test/abap/statements/move.ts
- packages/core/test/abap/statements/select.ts
- packages/core/test/rules/unused_methods.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.59.1, unused_methods fixes, no quick fixes inside macros

- .github/workflows/regression.yml
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/cli/src/cli.ts
- packages/cli/src/fixes.ts
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/scripts/schema.json
- packages/core/src/rules/prefer_inline.ts
- packages/core/test/rules/prefer_inline.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.59.2, quick fixes: fix infinite loop, show progress. Prefer inline fixes

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/5_syntax/statements/loop.ts
- packages/core/src/abap/types/basic/data_reference_type.ts
- packages/core/src/objects/rename/renamer_helper.ts
- packages/core/test/abap/syntax/syntax.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.59.6, bugfix, REFERENCE INTO

- packages/cli/src/fixes.ts
- packages/core/src/abap/5_syntax/_current_scope.ts
- packages/core/src/abap/5_syntax/basic_types.ts
- packages/core/src/ddic.ts
- packages/core/src/rules/index.ts
- packages/core/src/rules/intf_referencing_clas.ts
- packages/core/test/rules/intf_referencing_clas.ts
> 2.60.0, new rule: intf_referencing_clas

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/cli/src/cli.ts
- packages/cli/src/fixes.ts
- packages/core/package-lock.json
- packages/core/package.json
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.60.1, throw error for unknown version

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/2_statements/expressions/string_template_formatting.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.60.3, string template formatting version v740sp02

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/cli/src/fixes.ts
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/scripts/schema.json
- packages/core/scripts/schema.ts
- packages/core/src/rules/index.ts
- packages/core/src/rules/method_implemented_twice.ts
- packages/core/test/rules/method_implemented_twice.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.61.0, new rule method_implemented_twice

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/2_statements/expressions/index.ts
- packages/core/src/abap/2_statements/expressions/sql_field_list.ts
- packages/core/src/abap/2_statements/expressions/sql_from_source.ts
- packages/core/src/abap/2_statements/expressions/sql_path.ts
- packages/core/test/abap/statements/select.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.61.5, parser fixes

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/5_syntax/_builtin.ts
- packages/core/src/abap/5_syntax/_reference.ts
- packages/core/src/abap/5_syntax/basic_types.ts
- packages/core/src/abap/5_syntax/expressions/method_call_param.ts
- packages/core/src/abap/5_syntax/expressions/method_parameters.ts
- packages/core/src/abap/5_syntax/expressions/new_object.ts
- packages/core/src/rules/forbidden_void_type.ts
- packages/core/test/abap/syntax/syntax.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.61.8, infer NEW # type in method parameters

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/nodes/statement_node.ts
- packages/core/src/abap/types/basic/character_type.ts
- packages/core/src/abap/types/basic/floating_point_type.ts
- packages/core/src/abap/types/basic/hex_type.ts
- packages/core/src/abap/types/basic/packed_type.ts
- packages/core/src/abap/types/basic/unknown_type.ts
- packages/core/src/ddic.ts
- packages/core/src/objects/table_type.ts
- packages/core/src/rules/parser_missing_space.ts
- packages/core/src/rules/prefix_is_current_class.ts
- packages/core/test/objects/table_type.ts
- packages/core/test/rules/message_exists.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
* TTYP, dont qualify row if its basic, https://github.com/abaplint/transpiler/issues/151
* prefix_is_current_class performance
* `npm run test:parallel` target
* parser_missing_space, optimize performance
> 2.61.10, bugfixes

- package-lock.json
- package.json
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/2_statements/expressions/component_compare_simple.ts
- packages/core/src/abap/2_statements/expressions/index.ts
- packages/core/src/abap/2_statements/statements/read_table.ts
- packages/core/src/abap/5_syntax/expressions/new_object.ts
- packages/core/src/abap/5_syntax/statements/find.ts
- packages/core/test/abap/syntax/basic_variables.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
* READ TABLE expression refactoring
* closes #1593
* better error message for syntax errors with NEW
> 2.62.1, bugfixes

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/5_syntax/_reference.ts
- packages/core/src/abap/5_syntax/statements/method_implementation.ts
- packages/core/src/lsp/implementation.ts
- packages/core/test/lsp/hover.ts
- packages/core/test/lsp/implementation.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
method implementation references
> 2.62.3, goto method definition, goto method implementations

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/scripts/schema.json
- packages/core/scripts/schema.ts
- packages/core/src/lsp/_lookup.ts
- packages/core/src/rules/index.ts
- packages/core/src/rules/uncaught_exception.ts
- packages/core/test/rules/uncaught_exception.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.63.0, new rule uncaught_exception

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/5_syntax/statements/raise.ts
- packages/core/src/lsp/language_server.ts
- packages/core/test/abap/syntax/syntax.ts
- packages/core/test/lsp/formatting.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
- web/rules/package-lock.json
- web/rules/package.json
> 2.63.8, bugfix, pretty printer

- .github/workflows/regression.yml
- package-lock.json
- package.json
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/5_syntax/expressions/corresponding_body.ts
- packages/core/src/abap/5_syntax/expressions/source.ts
- packages/core/src/abap/5_syntax/structures/types.ts
- packages/core/src/rules/constructor_visibility_public.ts
- packages/core/src/rules/unused_methods.ts
- packages/core/test/abap/syntax/syntax.ts
- packages/core/test/rules/constructor_visibility_public.ts
- packages/core/test/rules/unused_methods.ts
- packages/core/test/rules/unused_variables.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
closes #1635
closes #1634
closes #1637
> 2.63.9, bugfixes

- packages/core/scripts/schema.json
- packages/core/src/rules/preferred_compare_operator.ts
This was just missing in documentation
> Add quickfix tag for preferred_compare_operator rule

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/5_syntax/_object_oriented.ts
- packages/core/test/abap/syntax/syntax.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.63.14, bugfix, ALIASed attribute

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/2_statements/statements/message.ts
- packages/core/src/abap/5_syntax/basic_types.ts
- packages/core/src/abap/5_syntax/expressions/method_source.ts
- packages/core/src/abap/5_syntax/statements/message.ts
- packages/core/src/abap/types/basic/table_type.ts
- packages/core/src/abap/types/interface_definition.ts
- packages/core/src/rules/check_subrc.ts
- packages/core/src/rules/prefix_is_current_class.ts
- packages/core/test/abap/statements/message.ts
- packages/core/test/abap/syntax/syntax.ts
- packages/core/test/lsp/hover.ts
- packages/core/test/rules/check_subrc.ts
- packages/core/test/rules/prefix_is_current_class.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
closes #1658
#1656
#1643
#1632
#1523
> 2.63.15, bugfixes

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/4_file_information/_abap_file_information.ts
- packages/core/src/abap/4_file_information/abap_file_information.ts
- packages/core/src/rules/implement_methods.ts
- packages/core/test/rules/implement_methods.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.63.16, bugfix, implement_methods

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/scripts/schema.json
- packages/core/scripts/schema.ts
- packages/core/src/abap/2_statements/expressions/constant_or_field_source.ts
- packages/core/src/abap/5_syntax/basic_types.ts
- packages/core/src/rules/index.ts
- packages/core/src/rules/use_class_based_exceptions.ts
- packages/core/test/abap/syntax/syntax.ts
- packages/core/test/rules/use_class_based_exceptions.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.64.0, new rule: use_class_based_exceptions

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/5_syntax/basic_types.ts
- packages/core/src/abap/5_syntax/expressions/new_object.ts
- packages/core/src/rules/_irule.ts
- packages/core/src/rules/check_subrc.ts
- packages/core/src/rules/unused_variables.ts
- packages/core/test/lsp/hover.ts
- packages/core/test/rules/forbidden_void_type.ts
- packages/core/test/rules/unused_variables.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
- web/rules/src/rule_page.ts
> 2.64.4, unused_variables, should respect pseudo comment, void type refs

- .github/workflows/coverage.yml
- .github/workflows/main.yml
- .github/workflows/playground.yml
- .github/workflows/regression.yml
- .github/workflows/syntax.yml
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/5_syntax/expressions/source.ts
- packages/core/src/rules/keep_single_parameter_on_one_line.ts
- packages/core/test/abap/syntax/basic_variables.ts
- packages/core/test/rules/keep_single_parameter_on_one_line.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.64.6: bugfixes, REF #, keep_single_parameter_on_one_line

- packages/core/scripts/schema.json
- packages/core/scripts/schema.ts
- packages/core/src/rules/index.ts
- packages/core/src/rules/prefer_raise_exception_new.ts
- packages/core/test/rules/prefer_raise_exception_new.ts
> Prefer RAISE EXCEPTION NEW to RAISE EXCEPTION TYPE - new rule

- package-lock.json
- package.json
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/2_statements/statements/system_call.ts
- packages/core/src/abap/5_syntax/statements/system_call.ts
- packages/core/src/abap/5_syntax/syntax.ts
- packages/core/test/abap/statements/system_call.ts
- packages/core/test/rules/unused_variables.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
- web/rules/src/rule_page.ts
> 2.65.3, rules.abaplint.org bugfix, system-call parsing fix

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/5_syntax/basic_types.ts
- packages/core/src/abap/5_syntax/expressions/attribute_name.ts
- packages/core/test/abap/syntax/syntax.ts
- packages/core/test/rules/unknown_types.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.66.1, bugfixes, dereference basic, LIKE REF TO

- docs/getting_started.md
- package-lock.json
- package.json
- packages/core/src/_iregistry.ts
- packages/core/src/abap/5_syntax/expressions/method_source.ts
- packages/core/src/rules/functional_writing.ts
- packages/core/test/abap/syntax/syntax.ts
> functional_writing, add example in docs

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/scripts/schema.json
- packages/core/src/abap/5_syntax/basic_types.ts
- packages/core/src/abap/5_syntax/statements/collect.ts
- packages/core/src/abap/5_syntax/syntax.ts
- packages/core/src/pretty_printer/pretty_printer.ts
- packages/core/src/rules/indentation.ts
- packages/core/test/lsp/hover.ts
- packages/core/test/rules/unused_variables.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.66.2, bugfixes

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/rules/allowed_object_naming.ts
- packages/core/test/rules/allowed_object_naming.ts
- packages/core/test/rules/unused_variables.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
- web/playground/src/index.ts
> 2.66.5, use monaco 0.21, fixes playground for now

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/5_syntax/basic_types.ts
- packages/core/src/abap/types/_class_attributes.ts
- packages/core/src/abap/types/class_attributes.ts
- packages/core/src/abap/types/class_definition.ts
- packages/core/src/abap/types/interface_definition.ts
- packages/core/src/abap/types/type_definitions.ts
- packages/core/src/rules/keyword_case.ts
- packages/core/test/abap/syntax/syntax.ts
- packages/core/test/rules/keyword_case.ts
- packages/core/test/rules/unused_variables.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.66.6, bugfixes

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/2_statements/expressions/select_loop.ts
- packages/core/src/abap/2_statements/expressions/sql_case.ts
- packages/core/src/abap/5_syntax/_current_scope.ts
- packages/core/src/abap/5_syntax/_spaghetti_scope.ts
- packages/core/src/abap/5_syntax/expressions/select.ts
- packages/core/src/abap/5_syntax/spaghetti_scope.ts
- packages/core/src/abap/5_syntax/statements/method_implementation.ts
- packages/core/src/abap/5_syntax/statements/update_database.ts
- packages/core/src/abap/5_syntax/syntax.ts
- packages/core/src/abap/types/class_definition.ts
- packages/core/src/abap/types/interface_definition.ts
- packages/core/src/registry.ts
- packages/core/test/abap/statements/select_loop.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.66.8, scope end position, SELECT CASE

- package-lock.json
- package.json
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/scripts/schema.json
- packages/core/src/abap/5_syntax/expressions/database_table.ts
- packages/core/src/abap/5_syntax/expressions/sql_from.ts
- packages/core/src/abap/5_syntax/statements/insert_database.ts
- packages/core/src/abap/5_syntax/statements/modify_database.ts
- packages/core/src/abap/5_syntax/statements/update_database.ts
- packages/core/src/abap/5_syntax/syntax.ts
- packages/core/src/rules/_irule.ts
- packages/core/src/rules/avoid_use.ts
- packages/core/src/rules/begin_end_names.ts
- packages/core/src/rules/call_transaction_authority_check.ts
- packages/core/src/rules/omit_parameter_name.ts
- packages/core/test/abap/syntax/syntax.ts
- packages/core/test/rules/begin_end_names.ts
- packages/core/test/rules/omit_parameter_name.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
- web/rules/package-lock.json
- web/rules/package.json
- web/rules/src/build.ts
- web/rules/src/common.ts
> 2.66.10, db table checks, omit_parameter_name quick fix

- .github/workflows/regression.yml
- package-lock.json
- package.json
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/scripts/schema.json
- packages/core/src/abap/5_syntax/expressions/field_chain.ts
- packages/core/src/rules/check_syntax.ts
- packages/core/src/rules/unknown_types.ts
- packages/core/test/abap/syntax/syntax.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.66.11, bugfix, voided FAE

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/scripts/schema.json
- packages/core/src/abap/3_structures/structures/_combi.ts
- packages/core/src/abap/3_structures/structures/method.ts
- packages/core/src/rules/max_one_statement.ts
- packages/core/src/rules/obsolete_statement.ts
- packages/core/test/abap/structures/class_implementation.ts
- packages/core/test/rules/obsolete_statement.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.67.1, NativeSQL bugfixes, RANGES is obsolete

- .github/regression/run.js
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/2_statements/combi.ts
- packages/core/src/abap/5_syntax/_current_scope.ts
- packages/core/src/abap/5_syntax/_object_oriented.ts
- packages/core/src/abap/5_syntax/_scope_type.ts
- packages/core/src/abap/5_syntax/_spaghetti_scope.ts
- packages/core/src/abap/5_syntax/expressions/for.ts
- packages/core/src/abap/5_syntax/expressions/reduce_body.ts
- packages/core/src/abap/5_syntax/expressions/target.ts
- packages/core/src/abap/5_syntax/expressions/value_body.ts
- packages/core/src/abap/5_syntax/spaghetti_scope.ts
- packages/core/src/abap/5_syntax/statements/create_object.ts
- packages/core/src/lsp/dump_scope.ts
- packages/core/src/lsp/references.ts
- packages/core/src/rules/forbidden_void_type.ts
- packages/core/src/rules/prefer_inline.ts
- packages/core/src/rules/unknown_types.ts
- packages/core/src/rules/unused_types.ts
- packages/core/src/rules/unused_variables.ts
- packages/core/test/abap/syntax/syntax.ts
- packages/core/test/rules/forbidden_void_type.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.68.0, duplicate name check for DATA and TYPES

- package-lock.json
- package.json
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/5_syntax/_current_scope.ts
- packages/core/src/abap/5_syntax/basic_types.ts
- packages/core/src/issue.ts
- packages/core/src/rules/unknown_types.ts
- packages/core/test/abap/syntax/basic_variables.ts
- packages/core/test/abap/syntax/syntax.ts
- packages/core/test/rules/unknown_types.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
allow LIKE ddic typing in PROGs
> 2.69.2, allow LIKE ddic typing in PROGs

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/2_statements/statement_parser.ts
- packages/core/src/abap/5_syntax/basic_types.ts
- packages/core/src/abap/5_syntax/structures/constants.ts
- packages/core/src/abap/types/_typed_identifier.ts
- packages/core/src/abap/types/class_constant.ts
- packages/core/src/objects/class.ts
- packages/core/test/abap/structures/exec_sql.ts
- packages/core/test/rules/unknown_types.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
* #1603
* closes #1797 
* dont dump if the CLAS xml is malformed
> 2.69.3, bugfixes

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/scripts/schema.json
- packages/core/scripts/schema.ts
- packages/core/src/rules/index.ts
- packages/core/src/rules/no_yoda_conditions.ts
- packages/core/src/rules/select_always_order_by.ts
- packages/core/test/rules/no_yoda_conditions.ts
- packages/core/test/rules/select_always_order_by.ts
- packages/core/test/rules/uncaught_exception.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.71.0, new rules: no_yoda_conditions & select_always_order_by

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/scripts/schema.json
- packages/core/src/abap/5_syntax/statements/pack.ts
- packages/core/src/abap/5_syntax/statements/unpack.ts
- packages/core/src/abap/5_syntax/syntax.ts
- packages/core/src/pretty_printer/indent.ts
- packages/core/src/rules/obsolete_statement.ts
- packages/core/test/rules/indentation.ts
- packages/core/test/rules/obsolete_statement.ts
- packages/core/test/rules/unused_variables.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.71.4, bugfixes

- package-lock.json
- package.json
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/5_syntax/statements/format.ts
- packages/core/src/abap/5_syntax/syntax.ts
- packages/core/src/rules/check_subrc.ts
- packages/core/test/rules/check_subrc.ts
- packages/core/test/rules/unused_variables.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.71.5, bugfixes

- package-lock.json
- package.json
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/scripts/schema.json
- packages/core/scripts/schema.ts
- packages/core/src/abap/2_statements/expressions/database_table.ts
- packages/core/src/abap/2_statements/statements/delete_database.ts
- packages/core/src/abap/2_statements/statements/insert_database.ts
- packages/core/src/abap/2_statements/statements/modify_database.ts
- packages/core/src/abap/2_statements/statements/update_database.ts
- packages/core/src/rules/check_subrc.ts
- packages/core/src/rules/index.ts
- packages/core/src/rules/modify_only_own_db_tables.ts
- packages/core/src/rules/unused_methods.ts
- packages/core/src/rules/unused_types.ts
- packages/core/src/rules/unused_variables.ts
- packages/core/test/rules/check_subrc.ts
- packages/core/test/rules/modify_only_own_db_tables.ts
- packages/core/test/rules/unused_methods.ts
- packages/core/test/rules/unused_types.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.72.0, new rule modify_only_own_db_tables, allow more pragmas

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
- web/playground/src/index.ts
- web/rules/package-lock.json
- web/rules/package.json
- web/rules/src/rule_page.ts
> 2.72.1 @abaplint/monaco: update monaco to latest

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/5_syntax/expressions/source.ts
- packages/core/src/rules/downport.ts
- packages/core/src/rules/no_yoda_conditions.ts
- packages/core/src/rules/prefer_xsdbool.ts
- packages/core/src/rules/sql_escape_host_variables.ts
- packages/core/src/rules/use_bool_expression.ts
- packages/core/test/abap/syntax/syntax.ts
- packages/core/test/rules/check_include.ts
- packages/core/test/rules/check_subrc.ts
- packages/core/test/rules/downport.ts
- packages/core/test/rules/no_yoda_conditions.ts
- packages/core/test/rules/use_bool_expression.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
* closes #1850
* add testcase, #1868
* add testcases, #1863
* closes #1373
* downport xsdbool, closes #1492
> 2.73.1, bugfixes

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/objects/rename/renamer_helper.ts
- packages/core/test/objects/rename/rename_global_class.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.73.3, bugfix, dont rename inferred references

- .github/regression/run.js
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/scripts/schema.json
- packages/core/src/abap/2_statements/result.ts
- packages/core/src/abap/types/function_module_definition.ts
- packages/core/src/objects/_abap_object.ts
- packages/core/src/objects/_abstract_object.ts
- packages/core/src/objects/class.ts
- packages/core/src/objects/data_element.ts
- packages/core/src/objects/domain.ts
- packages/core/src/objects/enhancement_spot.ts
- packages/core/src/objects/function_group.ts
- packages/core/src/objects/icf_service.ts
- packages/core/src/objects/interface.ts
- packages/core/src/objects/message_class.ts
- packages/core/src/objects/table.ts
- packages/core/src/objects/table_type.ts
- packages/core/src/objects/view.ts
- packages/core/src/rules/remove_descriptions.ts
- packages/core/src/xml_utils.ts
- packages/core/test/abap/syntax/syntax.ts
- packages/core/test/rules/allowed_object_naming.ts
- packages/core/test/rules/remove_descriptions.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.73.10, xml parser refactoring

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/2_statements/expand_macros.ts
- packages/core/src/position.ts
- packages/core/test/abap/macros.ts
- packages/core/test/abap/statements/clear.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.73.11, expand nested macros

- packages/core/src/rules/obsolete_statement.ts
- packages/core/test/rules/obsolete_statement.ts
- web/playground/package-lock.json
- web/playground/package.json
- web/rules/package-lock.json
- web/rules/package.json
- web/rules/src/build.ts
> bugfix, rules.abaplint.org updates

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/scripts/schema.json
- packages/core/src/abap/5_syntax/expressions/message_source.ts
- packages/core/src/abap/5_syntax/statements/message.ts
- packages/core/src/abap/5_syntax/statements/raise.ts
- packages/core/src/rules/modify_only_own_db_tables.ts
- packages/core/src/rules/select_performance.ts
- packages/core/test/rules/modify_only_own_db_tables.ts
- packages/core/test/rules/prefer_inline.ts
- packages/core/test/rules/select_performance.ts
- packages/core/test/rules/unused_variables.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
- web/rules/src/rule_page.ts
* select_performance, skip if APPENDING
* unused_variable, check MESSAGE parts
* modify_only_own_db_tables, fix false positive
> 2.74.13, bugfixes

- package-lock.json
- package.json
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/scripts/schema.json
- packages/core/src/objects/_abstract_object.ts
- packages/core/src/position.ts
- packages/core/src/rules/modify_only_own_db_tables.ts
- packages/core/src/rules/no_yoda_conditions.ts
- packages/core/src/rules/select_performance.ts
- packages/core/test/lsp/hover.ts
- packages/core/test/rules/modify_only_own_db_tables.ts
- packages/core/test/rules/no_yoda_conditions.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.74.19, bugfixes

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/scripts/schema.json
- packages/core/src/_iregistry.ts
- packages/core/src/abap/5_syntax/_spaghetti_scope.ts
- packages/core/src/abap/5_syntax/spaghetti_scope.ts
- packages/core/src/registry.ts
- packages/core/src/rules/select_performance.ts
- packages/core/test/rules/select_performance.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.74.20, select_performance, check number of columns

- package-lock.json
- package.json
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/5_syntax/_object_oriented.ts
- packages/core/test/lsp/hover.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.74.21, fix for nested interfaces

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/2_statements/combi.ts
- packages/core/src/abap/2_statements/result.ts
- packages/core/test/abap/combi.ts
- packages/core/test/abap/combi_size.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.74.29, statement parser optimizations

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/rules/forbidden_void_type.ts
- packages/core/test/rules/forbidden_void_type.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.74.30, bugfixes, forbidden_void_type

- package-lock.json
- package.json
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/5_syntax/expressions/inline_loop_definition.ts
- packages/core/src/abap/5_syntax/expressions/select.ts
- packages/core/test/abap/syntax/syntax.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.74.32, bugfixes

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/scripts/schema.json
- packages/core/src/ddic.ts
- packages/core/src/objects/data_definition.ts
- packages/core/test/objects/data_definition.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.74.35, start very basic DDLS parsing

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/2_statements/expressions/message_class.ts
- packages/core/src/abap/2_statements/expressions/select.ts
- packages/core/src/abap/2_statements/statements/select.ts
- packages/core/src/abap/3_structures/structures/normal.ts
- packages/core/src/ddic.ts
- packages/core/src/objects/data_definition.ts
- packages/core/test/abap/statements/raise.ts
- packages/core/test/abap/statements/select.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.74.37, bugfixes

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/scripts/schema.json
- packages/core/src/abap/2_statements/expressions/index.ts
- packages/core/src/abap/2_statements/expressions/ole_exporting.ts
- packages/core/src/abap/2_statements/statements/call_ole.ts
- packages/core/src/abap/2_statements/statements/get_property.ts
- packages/core/src/abap/2_statements/statements/set_property.ts
- packages/core/src/rules/global_class.ts
- packages/core/src/rules/implement_methods.ts
- packages/core/src/skip_logic.ts
- packages/core/test/rules/global_class.ts
- packages/core/test/rules/implement_methods.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
* bugfix, skipGeneratedGatewayClasses case
* OLE EXPORTING
* implement_methods: add quick fix
> 2.74.40, bugfixes

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/5_syntax/_object_oriented.ts
- packages/core/src/abap/5_syntax/statements/class_implementation.ts
- packages/core/src/abap/types/class_definition.ts
- packages/core/src/rules/implement_methods.ts
- packages/core/test/abap/syntax/syntax.ts
- packages/core/test/rules/implement_methods.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
* implement_methods, fix false positive
* bugfix, double interface implementation
> 2.74.42, bugfixes

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/2_statements/expressions/type_table.ts
- packages/core/src/abap/5_syntax/statements/find.ts
- packages/core/src/abap/types/form_definition.ts
- packages/core/test/abap/statements/data.ts
- packages/core/test/abap/syntax/syntax.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.74.44, bugfixes

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/5_syntax/_type_utils.ts
- packages/core/src/abap/5_syntax/statements/move.ts
- packages/core/src/abap/5_syntax/statements/shift.ts
- packages/core/src/abap/5_syntax/syntax.ts
- packages/core/src/abap/types/form_definition.ts
- packages/core/test/abap/syntax/syntax.ts
- packages/core/test/rules/unknown_types.ts
- packages/core/test/rules/unused_variables.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
* start basic type checking, table types and object references
* SHIFT unused var
* FORM STRUCTURE typing
> 2.74.45, bugfixes

- package-lock.json
- package.json
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/scripts/schema.json
- packages/core/src/abap/types/class_attributes.ts
- packages/core/src/rules/tabl_enhancement_category.ts
- packages/core/test/abap/syntax/syntax.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
* update api extractor
* bugfix, method default from enum
> 2.74.55, bugfix, method default from enum

- package-lock.json
- package.json
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/scripts/schema.json
- packages/core/scripts/schema.ts
- packages/core/src/_iddic_references.ts
- packages/core/src/_iregistry.ts
- packages/core/src/abap/5_syntax/basic_types.ts
- packages/core/src/abap/5_syntax/global_definitions/find_global_definitions.ts
- packages/core/src/ddic.ts
- packages/core/src/ddic_references.ts
- packages/core/src/objects/data_element.ts
- packages/core/src/registry.ts
- packages/core/src/rules/check_abstract.ts
- packages/core/src/rules/index.ts
- packages/core/src/rules/unused_ddic.ts
- packages/core/test/abap/syntax/basic_variables.ts
- packages/core/test/ddic_references.ts
- packages/core/test/rules/unused_ddic.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
* start #1881
* add `%_C_POINTER` built-in type
> 2.75.0, New rule, find unused DOMA

- package-lock.json
- package.json
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/scripts/schema.json
- packages/core/src/abap/5_syntax/basic_types.ts
- packages/core/src/ddic.ts
- packages/core/src/rules/rfc_error_handling.ts
- packages/core/src/rules/uncaught_exception.ts
- packages/core/test/rules/unused_ddic.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
- rfc_error_handling: add examples
- update uncaught_exception description
- bugfix, ddic parsing NUMC
- bugfix, ddic reference
> 2.75.5, bugfixes

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/5_syntax/_procedural.ts
- packages/core/src/abap/5_syntax/expressions/for.ts
- packages/core/src/abap/5_syntax/expressions/inline_loop_definition.ts
- packages/core/src/abap/5_syntax/syntax.ts
- packages/core/src/abap/types/function_module_definition.ts
- packages/core/test/rules/unused_variables.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
* FUGR, parameters, handle unknown and void better
* fix font on playground
* #2061
> 2.76.2, bugfixes

- package-lock.json
- package.json
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/5_syntax/_builtin.ts
- packages/core/src/abap/flow/statement_flow.ts
- packages/core/test/abap/flow/statement_flow.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
* bugfix SY-REPID is char 40
* some work on statement_flow, only used in unit testing, for now
> 2.76.5, bugfix, sy-repid is char 40

- packages/core/scripts/schema.json
- packages/core/src/rules/method_length.ts
- packages/core/src/utils/form_length_stats.ts
- packages/core/test/lsp/symbols.ts
- packages/core/test/rules/method_length.ts
> form_length rule

- packages/core/src/rules/obsolete_statement.ts
- packages/core/test/rules/obsolete_statement.ts
> obsolete syntax, SORT BY <fs>

- package-lock.json
- package.json
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/5_syntax/_builtin.ts
- packages/core/src/abap/5_syntax/expressions/field_chain.ts
- packages/core/src/abap/5_syntax/expressions/method_call_param.ts
- packages/core/src/abap/5_syntax/expressions/method_parameters.ts
- packages/core/src/abap/5_syntax/statements/create_object.ts
- packages/core/src/abap/types/_method_parameters.ts
- packages/core/src/abap/types/method_parameters.ts
- packages/core/test/abap/syntax/syntax.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.76.11, bugfix, required parameters

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/scripts/schema.json
- packages/core/src/abap/5_syntax/_type_utils.ts
- packages/core/src/abap/5_syntax/expressions/method_call_param.ts
- packages/core/src/abap/5_syntax/statements/read_table.ts
- packages/core/src/objects/interface.ts
- packages/core/src/rules/method_implemented_twice.ts
- packages/core/test/abap/syntax/syntax.ts
- packages/core/test/rules/method_implemented_twice.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
- web/rules/package-lock.json
- web/rules/package.json
closes #2094
closes #2092
closes #2089
closes #2093
> 2.76.12, bugfixes

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/rules/downport.ts
- packages/core/test/rules/downport.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
https://syntax.abaplint.org/?filter=tableex#/expression/TableExpression
> 2.77.2, downport table expressions

- package-lock.json
- package.json
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
- web/playground/webpack.config.js
no changes/fixes to linting logic
closes #2070
> 2.77.4, update monaco and css-loader

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/cli/src/cli.ts
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/scripts/schema.json
- packages/core/scripts/schema.ts
- packages/core/src/rules/index.ts
- packages/core/src/rules/pragma_placement.ts
- packages/core/test/rules/pragma_placement.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
- new rule pragma_placement, closes #119
- report error code 2 for generic errors, #2118
> 2.78.0, new rule pragma_placement & error code fix

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/5_syntax/expressions/new_object.ts
- packages/core/src/lsp/_interfaces.ts
- packages/core/src/lsp/language_server.ts
- packages/core/src/rules/downport.ts
- packages/core/test/rules/downport.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- packages/monaco/src/abap_semantic_tokens_delta_provider.ts
- packages/monaco/src/index.ts
- web/playground/package-lock.json
- web/playground/package.json
- web/playground/src/widgets/editor.ts
> 2.78.4, downport bugfix, start semantic highlighting

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/index.ts
- packages/core/src/lsp/language_server.ts
- packages/core/src/lsp/semantic.ts
- packages/core/src/rules/unreachable_code.ts
- packages/core/test/lsp/semantic.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- packages/monaco/src/abap_semantic_tokens_delta_provider.ts
- web/playground/package-lock.json
- web/playground/package.json
> 2.78.6, basic semantic highlighting

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/2_statements/statements/find.ts
- packages/core/src/abap/2_statements/statements/replace.ts
- packages/core/src/abap/3_structures/structures/_combi.ts
- packages/core/src/abap/5_syntax/_builtin.ts
- packages/core/src/lsp/semantic.ts
- packages/core/test/abap/abap_parser.ts
- packages/core/test/abap/statements/replace.ts
- packages/core/test/lsp/semantic.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
* changes to semantic highlighting
* closes #2129
* #2131
> 2.78.7, bugfixes

- package-lock.json
- package.json
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/5_syntax/_builtin.ts
- packages/core/src/abap/5_syntax/expressions/component_chain.ts
- packages/core/test/abap/syntax/syntax.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
https://github.com/abaplint/abaplint/issues/2137
> 2.78.9, bugfix, structured table_line

- .github/workflows/regression.yml
- package-lock.json
- package.json
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/cli/src/cli.ts
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/rules/use_line_exists.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
* fix `cli` check of version
* dont run `use_line_exists` on open-abap version
> 2.78.13, bugfixes

- .github/workflows/regression.yml
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/scripts/schema.json
- packages/core/src/abap/5_syntax/_type_utils.ts
- packages/core/src/lsp/semantic.ts
- packages/core/src/rules/downport.ts
- packages/core/test/abap/syntax/syntax.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
- web/playground/src/widgets/editor.ts
* semantic highlighting, bugfix INTERFACE
* #2144
* disable semantic highlighting on playground, https://github.com/abaplint/abaplint/issues/2145
> 2.79.0, bugfixes

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/5_syntax/expressions/field_assignment.ts
- packages/core/test/abap/syntax/syntax.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.79.2, bugfixes

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/issue.ts
- packages/core/src/rules/check_syntax.ts
- packages/core/test/rules/check_syntax.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.79.3, bugfix, check_syntax set severity

- package-lock.json
- package.json
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/2_statements/expressions/index.ts
- packages/core/src/abap/2_statements/expressions/string_template.ts
- packages/core/src/abap/2_statements/expressions/string_template_source.ts
- packages/core/src/abap/5_syntax/basic_types.ts
- packages/core/src/abap/5_syntax/expressions/string_template.ts
- packages/core/src/abap/types/basic/structure_type.ts
- packages/core/src/rules/reduce_string_templates.ts
- packages/core/test/abap/syntax/basic_variables.ts
- packages/core/test/rules/unknown_types.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
* refactor string template expression
* better error message, #2163
* refactor resolveLikeName()
> 2.79.5, bugfixes

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/objects/domain.ts
- packages/core/src/rules/downport.ts
- packages/core/test/objects/domain.ts
- packages/core/test/rules/downport.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.79.6, downport ALPHA, fix domain value parsing

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/objects/view.ts
- packages/core/src/rules/avoid_use.ts
- packages/core/test/objects/table.ts
- packages/core/test/objects/view.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
* avoid_use: add note regarding STATICS 
* handling VIEW APPENDS
> 2.79.8, handling VIEW APPENDS

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/scripts/schema.json
- packages/core/src/abap/types/method_definition.ts
- packages/core/src/rules/align_parameters.ts
- packages/core/test/lsp/hover.ts
- packages/core/test/rules/align_parameters.ts
- packages/core/test/rules/forbidden_void_type.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.80.1, align_parameters additions, bugfix RAISING references

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/scripts/schema.json
- packages/core/src/rules/align_parameters.ts
- packages/core/test/rules/align_parameters.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.80.3, align_parameters fix reported position

- package-lock.json
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/5_syntax/statements/get_cursor.ts
- packages/core/src/abap/5_syntax/syntax.ts
- packages/core/src/lsp/references.ts
- packages/core/src/rules/unused_types.ts
- packages/core/src/rules/unused_variables.ts
- packages/core/test/abap/syntax/syntax.ts
- packages/core/test/rules/unused_variables.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
this makes it run around 10 times faster on the abapGit source code
> 2.80.8, unused_variables performance

- package-lock.json
- package.json
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/5_syntax/expressions/field_assignment.ts
- packages/core/test/abap/syntax/syntax.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.80.8, deep VALUE assignment bugfix

- package-lock.json
- package.json
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/scripts/schema.json
- packages/core/src/abap/2_statements/expressions/sql_arithmetics.ts
- packages/core/src/abap/2_statements/expressions/sql_function.ts
- packages/core/src/abap/5_syntax/_current_scope.ts
- packages/core/src/abap/5_syntax/_scope_type.ts
- packages/core/src/abap/5_syntax/_spaghetti_scope.ts
- packages/core/src/abap/5_syntax/basic_types.ts
- packages/core/src/abap/5_syntax/spaghetti_scope.ts
- packages/core/src/abap/5_syntax/statements/class_implementation.ts
- packages/core/src/abap/5_syntax/statements/method_implementation.ts
- packages/core/src/abap/5_syntax/syntax.ts
- packages/core/src/rules/no_chained_assignment.ts
- packages/core/src/rules/unnecessary_chaining.ts
- packages/core/src/rules/unreachable_code.ts
- packages/core/test/abap/statements/select.ts
- packages/core/test/abap/syntax/syntax.ts
- packages/core/test/rules/unreachable_code.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.81.1, bugfixes

- packages/core/src/abap/5_syntax/_builtin.ts
- packages/core/src/lsp/_lookup.ts
- packages/core/test/lsp/hover.ts
Adds the method hover also for builtin methods (not even adt knows this btw). I also reformatted all the builtin signatures.
> Enable hover for builtin methods

- package-lock.json
- package.json
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/5_syntax/_object_oriented.ts
- packages/core/src/abap/5_syntax/statements/class_implementation.ts
- packages/core/src/abap/5_syntax/statements/method_implementation.ts
- packages/core/src/abap/nodes/expression_node.ts
- packages/core/src/abap/nodes/statement_node.ts
- packages/core/src/abap/types/class_definition.ts
- packages/core/src/edit_helper.ts
- packages/core/src/rules/parser_missing_space.ts
- packages/core/test/abap/syntax/syntax.ts
- packages/core/test/edit_helper.ts
- packages/core/test/rules/parser_missing_space.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.81.3, bugfixes

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/2_statements/statements/type_begin.ts
- packages/core/test/abap/structures/types.ts
- packages/core/test/abap/syntax/syntax.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.81.4, bugfix, Unexpected TYPEEND

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/rules/static_call_via_instance.ts
- packages/core/test/rules/static_call_via_instance.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.82.1, bugfix, static_call_via_instance

- package-lock.json
- package.json
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/2_statements/statements/index.ts
- packages/core/src/abap/2_statements/statements/type_mesh.ts
- packages/core/src/abap/2_statements/statements/type_mesh_begin.ts
- packages/core/src/abap/2_statements/statements/type_mesh_end.ts
- packages/core/src/abap/3_structures/structures/index.ts
- packages/core/src/abap/3_structures/structures/normal.ts
- packages/core/src/abap/3_structures/structures/section_section.ts
- packages/core/src/abap/3_structures/structures/type_mesh.ts
- packages/core/src/abap/5_syntax/expressions/field_chain.ts
- packages/core/src/objects/table.ts
- packages/core/test/abap/statements/type_mesh.ts
- packages/core/test/lsp/hover.ts
- packages/core/test/rules/parser_error.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
* fix void reference
* start adding MESH statement
* suffix named .INCLUDE
> 2.82.6, bugfixes

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/5_syntax/global_definitions/find_global_definitions.ts
- packages/core/src/objects/table.ts
- packages/core/test/abap/find_global_definitions.ts
- packages/core/test/objects/table.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
* bugfix for determining global types for constants
* parse ROLLNAME OBJECT
> 2.82.7, bugfix, count untyped constants

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/cli/src/index.ts
- packages/core/package-lock.json
- packages/core/package.json
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
ref https://github.com/abaplint/actions-abaplint/issues/21
> 2.82.10, cli, fix outputformat

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/types/basic/decfloat_type.ts
- packages/core/src/abap/types/basic/index.ts
- packages/core/src/ddic.ts
- packages/core/src/objects/table_type.ts
- packages/core/src/rules/unknown_types.ts
- packages/core/test/abap/syntax/basic_variables.ts
- packages/core/test/objects/table_type.ts
- packages/core/test/rules/unknown_types.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
* unknown_types bugfix
* add DECFLOAT
* TTYP type ref to DATA
> 2.82.11, bugfixes

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/5_syntax/_object_oriented.ts
- packages/core/src/abap/types/class_definition.ts
- packages/core/test/rules/unknown_types.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.82.12, bugfix, aliased types

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/scripts/schema.json
- packages/core/src/issue.ts
- packages/core/src/rules/space_before_colon.ts
- packages/core/test/rules/space_before_colon.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
space_before_colon quick fix, closes #2276
> 2.82.13, space_before_colon quick fix

- package-lock.json
- package.json
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/scripts/schema.json
- packages/core/src/rules/implement_methods.ts
- packages/core/src/rules/obsolete_statement.ts
- packages/core/test/rules/implement_methods.ts
- packages/core/test/rules/obsolete_statement.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
* closes #2287
* `implement_interfaces` bugfix, #2292
> 2.82.16, check for OCCURENCES + implement_interfaces bugfix

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/ddic.ts
- packages/core/src/objects/table.ts
- packages/core/test/objects/table.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.83.13, TABL GROUPNAME bugfix

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/rules/downport.ts
- packages/core/src/rules/unnecessary_chaining.ts
- packages/core/test/rules/downport.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.83.14, unnessesary_chaining & PARTIALLY IMPLEMENTED

- package-lock.json
- package.json
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/rules/align_parameters.ts
- packages/core/test/rules/align_parameters.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.83.18, bugfix, align_parameters

- package-lock.json
- package.json
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/rules/downport.ts
- packages/core/test/rules/downport.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.83.19, downport APPEND source expression

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/5_syntax/expressions/constant.ts
- packages/core/src/abap/5_syntax/expressions/source.ts
- packages/core/src/objects/_abstract_object.ts
- packages/core/src/objects/function_group.ts
- packages/core/src/rules/remove_descriptions.ts
- packages/core/src/rules/xml_consistency.ts
- packages/core/test/lsp/hover.ts
- packages/core/test/rules/downport.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.83.23, update to fast-xml-parser v4

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/5_syntax/expressions/database_table.ts
- packages/core/test/rules/unused_ddic.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.83.25, bugfix, unused_ddic

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/scripts/schema.json
- packages/core/scripts/schema.ts
- packages/core/src/rules/downport.ts
- packages/core/src/rules/index.ts
- packages/core/src/rules/method_length.ts
- packages/core/src/rules/omit_preceding_zeros.ts
- packages/core/test/rules/downport.ts
- packages/core/test/rules/omit_preceding_zeros.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
* new rule: omit_preceding_zeros, closes #2345
* closes #2294
* downport, bugfix, SELECT * INTO TABLE
> 2.84.0, new rule: omit_preceding_zeros

- package-lock.json
- package.json
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/5_syntax/_current_scope.ts
- packages/core/src/abap/5_syntax/_scope_type.ts
- packages/core/src/abap/5_syntax/basic_types.ts
- packages/core/src/abap/5_syntax/syntax.ts
- packages/core/src/abap/types/basic/data_reference_type.ts
- packages/core/src/ddic.ts
- packages/core/test/abap/syntax/basic_variables.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
* qualified names for type pool types
> 2.84.3, qualified names for type pool types

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/2_statements/expressions/type_table.ts
- packages/core/src/abap/5_syntax/basic_types.ts
- packages/core/src/abap/5_syntax/statements/read_table.ts
- packages/core/test/abap/statements/data.ts
- packages/core/test/abap/syntax/syntax.ts
- packages/core/test/rules/xml_consistency.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
* READ TABLE, check types
* bugfix, LIKE RANGE OF #2365
> 2.84.9, bugfixes

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/5_syntax/basic_types.ts
- packages/core/src/abap/types/class_definition.ts
- packages/core/test/abap/syntax/syntax.ts
- packages/core/test/rules/unknown_types.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
* bugfix, LIKE RANGE OF
* bugfix, EVENTS with handler in same class
> 2.85.2, bugfixes

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/2_statements/expressions/sql_alias_field.ts
- packages/core/src/abap/5_syntax/_object_oriented.ts
- packages/core/test/abap/syntax/syntax.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
* bugfix, interface constant referenced via class
* bugfix, SQLAliasField, allow namespace
> 2.85.3, bugfix, interface constant referenced via class

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/2_statements/expressions/sql_source.ts
- packages/core/test/abap/_utils.ts
- packages/core/test/abap/statements/select.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
bugfix, SQLSource, this will slow down performance?
> 2.85.4, bugfix, SQLSource

- package-lock.json
- package.json
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/2_statements/statements/assign.ts
- packages/core/src/abap/2_statements/statements/modify_internal.ts
- packages/core/test/abap/statements/modify_internal.ts
- packages/core/test/abap/syntax/syntax.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
* MODIFY bugfix
* ASSIGN bugfix
> 2.85.5, syntax bugfixes

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/2_statements/expressions/method_source.ts
- packages/core/src/abap/5_syntax/_type_utils.ts
- packages/core/test/abap/statements/call.ts
- packages/core/test/abap/syntax/syntax.ts
- packages/core/test/rules/functional_writing.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.85.7, bugfix, CALL METHOD + type checking

- .github/workflows/regression.yml
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/scripts/schema.json
- packages/core/src/abap/2_statements/expressions/type_table_key.ts
- packages/core/src/rules/identical_contents.ts
- packages/core/src/rules/local_testclass_location.ts
- packages/core/test/rules/keyword_case.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
* closes https://github.com/abaplint/abaplint/issues/2392
* bugfix https://github.com/abaplint/abaplint/issues/2391
> 2.85.10, bugfixes

- package-lock.json
- package.json
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/5_syntax/_type_utils.ts
- packages/core/test/abap/syntax/syntax.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.85.13, bugfix, WRITE table header line

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/5_syntax/basic_types.ts
- packages/core/src/rules/superclass_final.ts
- packages/core/test/rules/superclass_final.ts
- packages/core/test/rules/unknown_types.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.85.16, bugfix, voided type & superclass_final

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/5_syntax/expressions/method_source.ts
- packages/core/src/abap/5_syntax/expressions/sql_for_all_entries.ts
- packages/core/test/abap/syntax/syntax.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.85.23, bugfixes

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/2_statements/expressions/sql_as_name.ts
- packages/core/src/abap/2_statements/expressions/sql_field_list.ts
- packages/core/src/abap/5_syntax/expressions/source.ts
- packages/core/src/abap/5_syntax/expressions/switch_body.ts
- packages/core/src/rules/downport.ts
- packages/core/test/abap/statements/select.ts
- packages/core/test/abap/syntax/syntax.ts
- packages/core/test/rules/downport.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.85.24, downport, line_exists

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/2_statements/expressions/sql_compare.ts
- packages/core/src/abap/2_statements/expressions/sql_function.ts
- packages/core/src/abap/5_syntax/_builtin.ts
- packages/core/test/abap/statements/select.ts
- packages/core/test/abap/syntax/syntax.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
bugfix, col_group
bugfix, SELECT parsing
> 2.85.26, bugfixes

- packages/core/scripts/schema.json
- packages/core/src/rules/empty_structure.ts
- packages/core/test/rules/empty_structure.ts
> Empty WHEN reports error

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/3_structures/structures/constants.ts
- packages/core/test/abap/structures/constants.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.85.40, bugfix, CONSTANTS and INCLUDE

- package-lock.json
- package.json
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/utils/include_graph.ts
- packages/core/test/rules/check_include.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
https://github.com/abaplint/abaplint/issues/2446
> 2.85.41, bugfix, check_include

- docs/ci/README.md
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/rules/downport.ts
- packages/core/src/rules/select_add_order_by.ts
- packages/core/test/rules/downport.ts
- packages/core/test/rules/select_add_order_by.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
ref https://github.com/exercism/abap/issues/69
> 2.85.42, downport, bugfix

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/rules/downport.ts
- packages/core/test/rules/downport.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
* downport, #2452
* closes #2451
> 2.85.45, more downport

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/scripts/schema.json
- packages/core/scripts/schema.ts
- packages/core/src/abap/5_syntax/expressions/source.ts
- packages/core/src/rules/avoid_use.ts
- packages/core/src/rules/check_text_elements.ts
- packages/core/src/rules/downport.ts
- packages/core/src/rules/index.ts
- packages/core/src/rules/many_parentheses.ts
- packages/core/src/rules/nrob_consistency.ts
- packages/core/test/lsp/hover.ts
- packages/core/test/rules/avoid_use.ts
- packages/core/test/rules/downport.ts
- packages/core/test/rules/many_parentheses.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
closes #2457
closes #2459
closes #2406
> 2.86.0 - new rule nrob_sanitycheck

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/scripts/schema.json
- packages/core/src/rules/downport.ts
- packages/core/src/rules/unused_types.ts
- packages/core/src/rules/unused_variables.ts
- packages/core/test/rules/downport.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.86.4, downport, FOR, init var

- package-lock.json
- package.json
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/rules/double_space.ts
- packages/core/src/rules/downport.ts
- packages/core/test/rules/double_space.ts
- packages/core/test/rules/downport.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.86.7, double_space, workaround EVENTS

- package-lock.json
- package.json
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/scripts/schema.json
- packages/core/src/rules/downport.ts
- packages/core/src/rules/unsecure_fae.ts
- packages/core/test/rules/downport.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
- web/rules/src/build.ts
- web/rules/src/common.ts
> 2.86.8, downport bugfix + surface performance tag

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/scripts/schema.json
- packages/core/scripts/schema.ts
- packages/core/src/abap/types/_typed_identifier.ts
- packages/core/src/abap/types/method_parameters.ts
- packages/core/src/rules/index.ts
- packages/core/src/rules/slow_parameter_passing.ts
- packages/core/test/rules/slow_parameter_passing.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.87.0, new rule slow_parameter_passing

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/scripts/schema.json
- packages/core/scripts/schema.ts
- packages/core/src/rules/global_class.ts
- packages/core/src/rules/index.ts
- packages/core/src/rules/pragma_style.ts
- packages/core/src/rules/slow_parameter_passing.ts
- packages/core/src/rules/unnecessary_pragma.ts
- packages/core/test/rules/pragma_style.ts
- packages/core/test/rules/unnecessary_pragma.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
* rename rule `pragma_placment` -> `pragma_style`
* rename rule `check_no_handler_pragma` -> `unnecessary_pragma`
> 2.88.0, rename two rules, and extend logic

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/scripts/schema.json
- packages/core/scripts/schema.ts
- packages/core/src/abap/2_statements/expressions/index.ts
- packages/core/src/abap/2_statements/expressions/test_seam_name.ts
- packages/core/src/abap/2_statements/statements/test_injection.ts
- packages/core/src/abap/2_statements/statements/test_seam.ts
- packages/core/src/rules/index.ts
- packages/core/src/rules/no_external_form_calls.ts
- packages/core/test/abap/statements/test_seam.ts
- packages/core/test/rules/no_external_form_calls.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.90.0, new rule no_external_form_calls & bugfix, TEST-SEAM

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/scripts/schema.json
- packages/core/scripts/schema.ts
- packages/core/src/cds/expressions/cds_with_parameters.ts
- packages/core/src/objects/data_definition.ts
- packages/core/src/objects/table.ts
- packages/core/src/rules/cds_legacy_view.ts
- packages/core/src/rules/cds_parser_error.ts
- packages/core/src/rules/index.ts
- packages/core/src/rules/superfluous_value.ts
- packages/core/src/rules/unnecessary_pragma.ts
- packages/core/test/rules/cds_legacy_view.ts
- packages/core/test/rules/superfluous_value.ts
- packages/core/test/rules/unnecessary_pragma.ts
- packages/core/test/rules/unused_ddic.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
closes #2563
closes #2412
bugfix, #2390
closes #960
> 2.91.0, new rules superfluous_value + cds_legacy_view

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/5_syntax/_type_utils.ts
- packages/core/test/abap/syntax/syntax.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.91.1, bugfix, SimpleType

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/ddic.ts
- packages/core/src/objects/table.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
might fix https://github.com/abaplint/abaplint/issues/2568
> 2.91.2, bugfix

- packages/cli/src/formatters/junit.ts
Implements #2569
For instance:
Based on the `formatters/codeframe.ts`.
> Enhancing JUnit format

- package-lock.json
- package.json
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/2_statements/statements/get_locale.ts
- packages/core/src/abap/5_syntax/expressions/value_body.ts
- packages/core/src/rules/max_one_statement.ts
- packages/core/test/rules/max_one_statement.ts
- packages/core/test/rules/unused_variables.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
closes #2591
closes #2590
bugfix, unused variables, VALUE LINES OF
> 2.91.9, bugfixes

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/2_statements/expressions/perform_changing.ts
- packages/core/src/abap/5_syntax/statements/perform.ts
- packages/core/src/objects/event_binding.ts
- packages/core/src/objects/index.ts
- packages/core/src/rules/downport.ts
- packages/core/src/rules/sy_modification.ts
- packages/core/test/rules/sy_modification.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
closes #2618
closes #2621
closes #2623
> 2.91.22, bugfixes

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/5_syntax/statements/append.ts
- packages/core/test/rules/downport.ts
- packages/core/test/rules/unused_variables.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.91.25, bugfix, REFERENCE INTO inline

- package-lock.json
- package.json
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/2_statements/expressions/component_cond.ts
- packages/core/src/abap/2_statements/expressions/component_cond_sub.ts
- packages/core/src/abap/2_statements/expressions/index.ts
- packages/core/src/abap/2_statements/expressions/sql_client.ts
- packages/core/src/abap/2_statements/statements/insert_internal.ts
- packages/core/src/abap/5_syntax/expressions/component_cond.ts
- packages/core/src/abap/5_syntax/statements/append.ts
- packages/core/src/abap/5_syntax/statements/insert_field_group.ts
- packages/core/src/abap/5_syntax/syntax.ts
- packages/core/src/index.ts
- packages/core/src/rules/many_parentheses.ts
- packages/core/src/rules/parser_missing_space.ts
- packages/core/test/abap/statements/insert_internal.ts
- packages/core/test/abap/syntax/syntax.ts
- packages/core/test/rules/downport.ts
- packages/core/test/rules/many_parentheses.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
closes https://github.com/abaplint/abaplint/issues/2646
closes https://github.com/abaplint/abaplint/issues/2640
closes #2639
> 2.91.33, bugfixes

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/2_statements/combi.ts
- packages/core/src/abap/2_statements/expressions/type_table.ts
- packages/core/src/abap/2_statements/expressions/type_table_key.ts
- packages/core/src/abap/2_statements/statements/loop.ts
- packages/core/src/abap/2_statements/statements/read_table.ts
- packages/core/src/abap/5_syntax/expressions/type_table_key.ts
- packages/core/src/cds/expressions/cds_condition.ts
- packages/core/test/abap/statements/type.ts
- packages/core/test/rules/keyword_case.ts
- packages/core/test/rules/unknown_types.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.91.34, bugfixes

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/5_syntax/expressions/method_call_param.ts
- packages/core/src/objects/api_release_state.ts
- packages/core/src/objects/index.ts
- packages/core/src/rules/rfc_error_handling.ts
- packages/core/test/abap/syntax/syntax.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.91.38, syntax check, bugfix

- docs/getting_started.md
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/2_statements/expressions/index.ts
- packages/core/src/abap/2_statements/expressions/value_body.ts
- packages/core/src/abap/2_statements/expressions/value_body_line.ts
- packages/core/src/abap/5_syntax/expressions/value_body.ts
- packages/core/src/rules/align_parameters.ts
- packages/core/src/rules/downport.ts
- packages/core/src/rules/parser_missing_space.ts
- packages/core/test/rules/align_parameters.ts
- packages/core/test/rules/unused_variables.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.92.2, align_parameters, bugfix

- package-lock.json
- package.json
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/cli/src/fixes.ts
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/scripts/schema.json
- packages/core/src/abap/2_statements/statements/form.ts
- packages/core/src/abap/2_statements/statements/form_definition.ts
- packages/core/src/abap/2_statements/statements/index.ts
- packages/core/src/abap/3_structures/structures/normal.ts
- packages/core/src/abap/5_syntax/expressions/value_body.ts
- packages/core/src/rules/obsolete_statement.ts
- packages/core/src/rules/prefer_corresponding.ts
- packages/core/src/rules/sicf_consistency.ts
- packages/core/test/abap/statements/form.ts
- packages/core/test/abap/statements/form_definition.ts
- packages/core/test/abap/syntax/syntax.ts
- packages/core/test/rules/obsolete_statement.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
closes #2667
closes #2669
closes #2581
closes #2561
> 2.93.8, bugfixes

- package-lock.json
- package.json
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/2_statements/expressions/for.ts
- packages/core/src/rules/downport.ts
- packages/core/test/rules/downport.ts
- packages/core/test/rules/many_parentheses.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
https://github.com/exercism/abap/issues/179
#2672
> 2.93.10, bugfixes, downport & many_parentheses

- package-lock.json
- package.json
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/5_syntax/statements/sort.ts
- packages/core/test/abap/syntax/syntax.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.93.11, SORT, check fields

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/5_syntax/expressions/inline_field_definition.ts
- packages/core/src/abap/5_syntax/expressions/reduce_body.ts
- packages/core/src/rules/downport.ts
- packages/core/test/rules/_utils.ts
- packages/core/test/rules/downport.ts
- packages/core/test/rules/implement_methods.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
https://github.com/exercism/abap/issues/186
> 2.93.18, downport, bugfixes

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/5_syntax/expressions/loop_group_by.ts
- packages/core/src/rules/downport.ts
- packages/core/test/abap/syntax/syntax.ts
- packages/core/test/rules/_utils.ts
- packages/core/test/rules/downport.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
https://github.com/exercism/abap/issues/190
> 2.93.21, LOOP GROUP BY, syntax check fixes

- packages/cli/README.md
- packages/cli/src/formatters/_format.ts
- packages/cli/src/formatters/checkstyle.ts
- packages/cli/src/formatters/index.ts
- packages/cli/src/index.ts
Ref: https://checkstyle.sourceforge.io/
Jenkins plugin: https://github.com/jenkinsci/warnings-ng-plugin
> Adding Checkstyle Format

- package-lock.json
- package.json
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/pretty_printer/indent.ts
- packages/core/src/rules/abapdoc.ts
- packages/core/src/rules/main_file_contents.ts
- packages/core/src/rules/unnecessary_pragma.ts
- packages/core/test/rules/abapdoc.ts
- packages/core/test/rules/indentation.ts
- packages/core/test/rules/main_file_contents.ts
- packages/core/test/rules/unnecessary_pragma.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.93.45: bugfixes

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/rules/downport.ts
- packages/core/test/rules/downport.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
https://github.com/exercism/abap/issues/68
> 2.93.78: downport, renaming of duplicate variable names

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/rules/downport.ts
- packages/core/test/rules/downport.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
https://github.com/exercism/abap/issues/194
https://github.com/exercism/abap/issues/200
> 2.93.80: downport, bugfix

- package-lock.json
- package.json
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/cds/expressions/cds_arithmetics.ts
- packages/core/src/cds/expressions/cds_case.ts
- packages/core/src/cds/expressions/cds_element.ts
- packages/core/src/cds/expressions/cds_function.ts
- packages/core/test/cds/cds_parser.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.93.85: optimize CDS parsing

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/5_syntax/basic_types.ts
- packages/core/src/abap/5_syntax/expressions/data_definition.ts
- packages/core/src/abap/5_syntax/statements/class_data.ts
- packages/core/src/abap/5_syntax/statements/data.ts
- packages/core/src/abap/types/class_attribute.ts
- packages/core/src/abap/types/class_attributes.ts
- packages/core/test/objects/class.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
https://github.com/abaplint/transpiler/issues/891
> 2.93.92: parse data VALUEs in class attributes

- package-lock.json
- package.json
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/scripts/schema.json
- packages/core/scripts/schema.ts
- packages/core/src/abap/1_lexer/lexer.ts
- packages/core/src/abap/flow/flow_graph.ts
- packages/core/src/abap/flow/statement_flow.ts
- packages/core/src/rules/if_in_if.ts
- packages/core/src/rules/index.ts
- packages/core/src/rules/unnecessary_return.ts
- packages/core/test/rules/if_in_if.ts
- packages/core/test/rules/unnecessary_return.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- packages/morph/.gitignore
- packages/morph/abap/zcl_alint_lexer.clas.locals_imp.abap
- packages/morph/abap/zcl_alint_lexer.clas.testclasses.abap
- packages/morph/abap_transpile.json
- packages/morph/package.json
- packages/morph/src/expressions/call.ts
- packages/morph/src/statements/class_declaration.ts
- packages/morph/test/test.ts
- web/playground/package-lock.json
- web/playground/package.json
> 2.94.0: new rule unnecessary_return & quick fix for if_in_if

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/5_syntax/statements/loop.ts
- packages/core/src/rules/prefer_corresponding.ts
- packages/core/test/abap/syntax/syntax.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.94.17: bugfix LOOP INTO syntax check

- package-lock.json
- package.json
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/cds/expressions/cds_define_custom.ts
- packages/core/src/objects/authorization_check_field.ts
- packages/core/src/objects/lock_object.ts
- packages/core/src/objects/maintenance_and_transport_object.ts
- packages/core/src/rules/check_ddic.ts
- packages/core/test/cds/cds_parser.ts
- packages/core/test/objects/maintenance_and_transport_object.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
plus fix minor CDS parsing error
> 2.94.21: parse TOBJ

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/2_statements/expressions/sql_field_list_loop.ts
- packages/core/src/abap/2_statements/expressions/sql_function.ts
- packages/core/test/abap/statements/select_loop.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.94.22: SELECT bugfixes

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/2_statements/expressions/method_source.ts
- packages/core/src/abap/5_syntax/expressions/field_chain.ts
- packages/core/src/abap/5_syntax/expressions/method_source.ts
- packages/core/src/abap/5_syntax/expressions/source_field.ts
- packages/core/test/abap/syntax/syntax.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.94.25: refactor MethodSource

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/5_syntax/statements/parameter.ts
- packages/core/src/abap/5_syntax/statements/selectoption.ts
- packages/core/src/objects/table.ts
- packages/core/src/objects/view.ts
- packages/core/src/rules/allowed_object_naming.ts
- packages/core/test/abap/syntax/syntax.ts
- packages/core/test/rules/allowed_object_naming.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
- TABL length fix
- PARAMETERS length fix
- SELECT-OPTIONS length fix
> 2.95.12: bugfix, name lengths

- package-lock.json
- package.json
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/2_statements/expressions/write_offset_length.ts
- packages/core/src/abap/5_syntax/statements/write.ts
- packages/core/test/rules/unused_variables.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.95.14: bugfix, WRITE AT

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/objects/data_definition.ts
- packages/core/test/objects/data_definition.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
yea, this is an evil workaround..
> 2.95.22: CDS parsing, bugfix

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/2_statements/expressions/inlinedata.ts
- packages/core/src/abap/2_statements/statements/import.ts
- packages/core/src/abap/5_syntax/expressions/component_compare.ts
- packages/core/src/rules/uncaught_exception.ts
- packages/core/test/abap/statements/import.ts
- packages/core/test/abap/statements/move.ts
- packages/core/test/rules/uncaught_exception.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.95.25: syntax, add FINAL & uncaught_exception

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/2_statements/statements/at.ts
- packages/core/src/abap/2_statements/statements/at_first.ts
- packages/core/src/abap/2_statements/statements/at_last.ts
- packages/core/src/abap/2_statements/statements/index.ts
- packages/core/src/abap/3_structures/structures/at_first.ts
- packages/core/src/abap/3_structures/structures/at_last.ts
- packages/core/src/abap/3_structures/structures/index.ts
- packages/core/src/abap/3_structures/structures/normal.ts
- packages/core/src/pretty_printer/indent.ts
- packages/core/src/rules/empty_structure.ts
- packages/core/test/abap/statements/at.ts
- packages/core/test/abap/statements/at_first.ts
- packages/core/test/abap/statements/at_last.ts
- packages/core/test/rules/indentation.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.95.28: refactor AT

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/rules/downport.ts
- packages/core/test/rules/downport.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
- web/playground/src/widgets/editor.ts
> 2.95.31: downport bugfix

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/2_statements/statements/method_def.ts
- packages/core/test/abap/statements/method_def.ts
- packages/core/test/rules/downport.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.95.32: syntax, FOR LOCK

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/5_syntax/basic_types.ts
- packages/core/src/abap/types/basic/data_reference_type.ts
- packages/core/src/abap/types/basic/table_type.ts
- packages/core/src/rules/downport.ts
- packages/core/test/abap/syntax/syntax.ts
- packages/core/test/rules/downport.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.95.34: bugfixes

- packages/core/src/rules/function_module_recommendations.ts
POPUP_TO_CONFIRM_STEP is obsolete since long ago, use POPUP_TO_CONFIRM instead
> Add POPUP_TO_CONFIRM_STEP to function_module_recommendations

- packages/core/src/rules/abapdoc.ts
- packages/core/test/rules/abapdoc.ts
Hi, I needed the abapdoc rule to check if something really is inside it. I came up with this solution.
> Abapdoc rule improvements

- package-lock.json
- package.json
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/scripts/schema.json
- packages/core/scripts/schema.ts
- packages/core/src/_config.ts
- packages/core/src/abap/2_statements/expressions/select.ts
- packages/core/src/rules/colon_missing_space.ts
- packages/core/src/rules/index.ts
- packages/core/src/rules/select_single_full_key.ts
- packages/core/test/abap/statements/select.ts
- packages/core/test/rules/colon_missing_space.ts
- packages/core/test/rules/select_single_full_key.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.98.0: new rule select_single_full_key

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/scripts/schema.json
- packages/core/scripts/schema.ts
- packages/core/src/objects/mime_object.ts
- packages/core/src/rules/index.ts
- packages/core/src/rules/msag_consistency.ts
- packages/core/src/rules/omit_preceding_zeros.ts
- packages/core/src/rules/smim_consistency.ts
- packages/core/test/rules/omit_preceding_zeros.ts
- packages/core/test/rules/smim_consistency.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
new rule smim_consistency + bugfix omit_preceding_zeros
> 2.99.0: new rule smim_consistency

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/.npmignore
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/scripts/schema.json
- packages/core/scripts/schema_post.js
- packages/core/src/_config.ts
- packages/core/src/config.ts
- packages/core/src/objects/rename/rename_data_element.ts
- packages/core/src/objects/rename/renamer_helper.ts
- packages/core/src/rules/check_comments.ts
- packages/core/src/rules/unnecessary_pragma.ts
- packages/core/test/objects/rename/rename_data_element.ts
- packages/core/test/rules/unnecessary_pragma.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
- web/syntax/generate.mjs
- web/syntax/public/script.js
> 2.99.6: minor bugfixes

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/rules/strict_sql.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
instead of max one issue per file
https://rules.abaplint.org/strict_sql/
> 2.99.8: strict_sql, report all issues

- package-lock.json
- package.json
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/5_syntax/statements/tables.ts
- packages/core/src/lsp/_lookup.ts
- packages/core/src/objects/program.ts
- packages/core/src/rules/main_file_contents.ts
- packages/core/test/lsp/hover.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.99.9: main_file_contents, bugfix for module pools

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/5_syntax/_builtin.ts
- packages/core/src/abap/5_syntax/_type_utils.ts
- packages/core/src/rules/select_add_order_by.ts
- packages/core/test/abap/syntax/syntax.ts
- packages/core/test/rules/select_add_order_by.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.99.11: bugfix, select_add_order_by + stronger typing

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/scripts/schema.json
- packages/core/scripts/schema.ts
- packages/core/src/_imsag_references.ts
- packages/core/src/_iregistry.ts
- packages/core/src/abap/5_syntax/_current_scope.ts
- packages/core/src/abap/5_syntax/expressions/message_source.ts
- packages/core/src/abap/5_syntax/statements/raise.ts
- packages/core/src/abap/5_syntax/syntax.ts
- packages/core/src/abap/types/message.ts
- packages/core/src/ddic_references.ts
- packages/core/src/msag_references.ts
- packages/core/src/objects/message_class.ts
- packages/core/src/registry.ts
- packages/core/src/rules/easy_to_find_messages.ts
- packages/core/src/rules/index.ts
- packages/core/src/rules/msag_consistency.ts
- packages/core/test/msag_references.ts
- packages/core/test/rules/easy_to_find_messages.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.100.1: new rule `easy_to_find_messages`

- .github/workflows/regression.yml
- package-lock.json
- package.json
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/scripts/schema.json
- packages/core/src/abap/5_syntax/expressions/source.ts
- packages/core/src/ddic.ts
- packages/core/src/rules/empty_line_in_statement.ts
- packages/core/test/objects/domain.ts
- packages/core/test/objects/table_type.ts
- packages/core/test/rules/downport.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.100.3: downport, bugfix

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/rules/reduce_string_templates.ts
- packages/core/test/rules/reduce_string_templates.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.100.6: bugfix, reduce_string_templates

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/2_statements/expressions/index.ts
- packages/core/src/abap/2_statements/expressions/sql_arithmetic_operator.ts
- packages/core/src/abap/2_statements/expressions/sql_arithmetics.ts
- packages/core/src/abap/2_statements/expressions/sql_field_and_value.ts
- packages/core/src/rules/downport.ts
- packages/core/test/abap/statements/update_database.ts
- packages/core/test/rules/downport.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.101.8: fail for downport error

- package-lock.json
- package.json
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/5_syntax/_spaghetti_scope.ts
- packages/core/src/abap/5_syntax/_type_utils.ts
- packages/core/src/abap/5_syntax/spaghetti_scope.ts
- packages/core/src/abap/types/basic/index.ts
- packages/core/src/abap/types/basic/integer8_type.ts
- packages/core/src/ddic.ts
- packages/core/src/lsp/_lookup.ts
- packages/core/src/lsp/rename.ts
- packages/core/test/abap/syntax/basic_variables.ts
- packages/core/test/abap/syntax/syntax.ts
- packages/core/test/lsp/rename_variable.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.101.9: syntax bugfix & method rename & parameter rename

- .github/regression/run.js
- package-lock.json
- package.json
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/lsp/rename.ts
- packages/core/src/rules/downport.ts
- packages/core/src/rules/empty_structure.ts
- packages/core/test/lsp/rename_method.ts
- packages/core/test/lsp/rename_variable.ts
- packages/core/test/rules/downport.ts
- packages/core/test/rules/empty_structure.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
closes #3011
plus downport fix, plus rename fix
> 2.101.10: bugfix, empty_structure

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/scripts/schema.json
- packages/core/src/abap/5_syntax/_type_utils.ts
- packages/core/src/abap/5_syntax/basic_types.ts
- packages/core/src/abap/5_syntax/expressions/method_param.ts
- packages/core/src/abap/types/basic/hex_type.ts
- packages/core/src/abap/types/basic/index.ts
- packages/core/src/abap/types/basic/xgeneric_type.ts
- packages/core/src/rules/align_parameters.ts
- packages/core/src/rules/fully_type_itabs.ts
- packages/core/src/rules/select_single_full_key.ts
- packages/core/test/abap/syntax/syntax.ts
- packages/core/test/lsp/inlay_hints.ts
- packages/core/test/rules/align_parameters.ts
- packages/core/test/rules/downport.ts
- packages/core/test/rules/fully_type_itabs.ts
- packages/monaco/README.md
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
- web/rules/package-lock.json
- web/rules/package.json
- web/rules/src/monaco_abap.ts
> 2.101.16: downport bugfix, quickfix for align_parameters

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/scripts/schema.json
- packages/core/src/abap/5_syntax/_current_scope.ts
- packages/core/src/abap/5_syntax/_type_utils.ts
- packages/core/src/abap/5_syntax/expressions/attribute_chain.ts
- packages/core/src/abap/5_syntax/expressions/attribute_name.ts
- packages/core/src/abap/5_syntax/expressions/field_chain.ts
- packages/core/src/abap/5_syntax/expressions/method_call_param.ts
- packages/core/src/abap/5_syntax/expressions/source.ts
- packages/core/src/abap/5_syntax/expressions/source_field.ts
- packages/core/src/abap/5_syntax/statements/loop.ts
- packages/core/src/rules/align_parameters.ts
- packages/core/src/rules/unnecessary_pragma.ts
- packages/core/test/abap/syntax/spaghetti_scope.ts
- packages/core/test/abap/syntax/syntax.ts
- packages/core/test/rules/slow_parameter_passing.ts
- packages/core/test/rules/unnecessary_pragma.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.101.17: bugfixes

- package-lock.json
- package.json
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/2_statements/expressions/sql_aggregation.ts
- packages/core/test/abap/statements/select.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.101.27: bugfix, SELECT syntax

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/scripts/schema.json
- packages/core/scripts/schema.ts
- packages/core/src/rules/function_module_recommendations.ts
- packages/core/src/rules/index.ts
- packages/core/src/rules/prefer_pragmas.ts
- packages/core/src/rules/unnecessary_return.ts
- packages/core/test/rules/prefer_pragmas.ts
- packages/core/test/rules/unnecessary_return.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
- web/rules/package-lock.json
- web/rules/package.json
* more intelligent `unnecessary_return`
* another fm recommendation
* #3022
> 2.102.0: new rule `prefer_pragmas`

- docs/getting_started.md
- package-lock.json
- package.json
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/5_syntax/_procedural.ts
- packages/core/src/abap/5_syntax/expressions/method_parameters.ts
- packages/core/src/rules/prefer_pragmas.ts
- packages/core/test/abap/syntax/syntax.ts
- packages/core/test/rules/unused_types.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.102.3: bugfix, unused_types

- package-lock.json
- package.json
- packages/core/src/abap/5_syntax/statements/include_type.ts
- packages/core/src/abap/types/basic/structure_type.ts
- web/rules/package-lock.json
- web/rules/package.json
- web/rules/public/index.js
- web/rules/src/build.ts
- web/rules/src/common.ts
- web/rules/tsconfig.json
- web/rules/webpack.config.js
> new rules.abaplint.org search

- package-lock.json
- package.json
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/rules/unnecessary_pragma.ts
- packages/core/test/rules/unnecessary_pragma.ts
- packages/core/test/rules/unused_variables.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
https://github.com/abaplint/abaplint/issues/3075
> 2.102.22: unnecessary_pragma bugfix

- .github/regression/run.js
- package-lock.json
- package.json
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/2_statements/statements/loop.ts
- packages/core/src/abap/2_statements/statements/read_textpool.ts
- packages/core/src/abap/5_syntax/statements/read_textpool.ts
- packages/core/src/rules/message_exists.ts
- packages/core/test/abap/statements/loop.ts
- packages/core/test/abap/statements/read_textpool.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
https://github.com/abaplint/abaplint/pull/3094
> 2.102.35: LOOP STEP

- package-lock.json
- package.json
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/rules/check_subrc.ts
- packages/core/test/rules/check_subrc.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.102.43: bugfix, check_subrc

- package-lock.json
- package.json
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/scripts/schema.json
- packages/core/src/abap/5_syntax/expressions/select.ts
- packages/core/src/abap/types/message.ts
- packages/core/src/rules/msag_consistency.ts
- packages/core/test/abap/types/message.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.102.52: more msag_consistency + SELECT inline JOIN

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/2_statements/expressions/sql_fields.ts
- packages/core/test/abap/statements/select.ts
- packages/core/test/rules/downport.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.102.53: bugfix, SELECT FIELDS

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/1_lexer/lexer.ts
- packages/core/src/rules/unreachable_code.ts
- packages/core/test/abap/statement_parser.ts
- packages/core/test/rules/unreachable_code.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.102.55: bugfix, string template lexing + unreachable_code

- packages/cli/src/formatters/_format.ts
- packages/cli/src/formatters/codeclimate.ts
- packages/cli/src/formatters/index.ts
- packages/cli/src/formatters/sonarqube.ts
> codeclimate and sonarqube formatter

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/scripts/schema.json
- packages/core/src/rules/select_add_order_by.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.102.58: select_add_order_by: add option to skip FAE

- package-lock.json
- package.json
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/5_syntax/expressions/select.ts
- packages/core/src/abap/5_syntax/expressions/sql_order_by.ts
- packages/core/src/abap/types/interface_definition.ts
- packages/core/src/objects/rename/rename_message_class.ts
- packages/core/src/objects/rename/renamer.ts
- packages/core/test/abap/syntax/syntax.ts
- packages/core/test/objects/rename/rename_message_class.ts
- packages/core/test/rules/unused_variables.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
* bugfix, unused variable in SELECT ORDER BY dynamic
* error if CONSTRUCTOR method defined in interface
* renaming of MSAG
> 2.102.59: bugfix, unused variable + rename MSAG

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/objects/index.ts
- packages/core/src/objects/oauth2_profile.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.103.8: add OA2P

- package-lock.json
- package.json
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/2_statements/expressions/assign_source.ts
- packages/core/src/abap/5_syntax/statements/assign.ts
- packages/core/test/abap/statements/assign.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.103.10: bugfix, ASSIGN 702 syntax

- package-lock.json
- package.json
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/2_statements/statements/end_test_seam.ts
- packages/core/src/abap/2_statements/statements/test_seam.ts
- packages/core/src/abap/5_syntax/expressions/inline_data.ts
- packages/core/src/rules/downport.ts
- packages/core/test/abap/syntax/syntax.ts
- packages/core/test/rules/downport.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.105.13: bugfixes

- .github/workflows/regression.yml
- package-lock.json
- package.json
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/5_syntax/_type_utils.ts
- packages/core/src/rules/uncaught_exception.ts
- packages/core/test/abap/syntax/syntax.ts
- packages/core/test/rules/uncaught_exception.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.105.15: bugfixes

- package-lock.json
- package.json
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/cli/src/formatters/junit.ts
- packages/core/package-lock.json
- packages/core/package.json
- packages/monaco/package-lock.json
- packages/monaco/package.json
> 2.105.23: fix junit xml

- package-lock.json
- package.json
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/scripts/schema.json
- packages/core/scripts/schema.ts
- packages/core/src/abap/2_statements/statements/concatenate.ts
- packages/core/src/abap/5_syntax/_procedural.ts
- packages/core/src/abap/5_syntax/expressions/source.ts
- packages/core/src/abap/5_syntax/statements/concatenate.ts
- packages/core/src/rules/identical_conditions.ts
- packages/core/src/rules/index.ts
- packages/core/src/rules/invalid_table_index.ts
- packages/core/src/rules/slow_parameter_passing.ts
- packages/core/src/rules/strict_sql.ts
- packages/core/test/abap/statements/concatenate.ts
- packages/core/test/abap/syntax/fugr_import_export.ts
- packages/core/test/abap/syntax/syntax.ts
- packages/core/test/rules/invalid_table_index.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
- web/rules/package-lock.json
- web/rules/package.json
closes #3258
closes #3257
closes #3256
#3262
> 2.106.0: additional examples + check hex + new rule

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/2_statements/expressions/target.ts
- packages/core/src/abap/5_syntax/expressions/target.ts
- packages/core/test/abap/syntax/syntax.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.106.7: bugfix CAST

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/scripts/schema.json
- packages/core/src/abap/5_syntax/expressions/select.ts
- packages/core/src/abap/5_syntax/expressions/sql_compare.ts
- packages/core/src/rules/no_prefixes.ts
- packages/core/test/rules/no_prefixes.ts
- packages/core/test/rules/unused_variables.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
- web/rules/package-lock.json
- web/rules/package.json
> 2.106.9: bugfix no_prefixes

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/cli/src/fixes.ts
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/index.ts
- packages/core/src/issue.ts
- packages/core/src/lsp/_edit.ts
- packages/core/src/lsp/code_actions.ts
- packages/core/src/rules/chain_mainly_declarations.ts
- packages/core/test/rules/_utils.ts
- packages/core/test/rules/downport.ts
- packages/core/test/rules/unused_types.ts
- packages/core/test/rules/unused_variables.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
- web/rules/package-lock.json
- web/rules/package.json
> 2.107.3: multiple + default quick fixes for issues

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/scripts/schema.json
- packages/core/scripts/schema.ts
- packages/core/src/rules/align_pseudo_comments.ts
- packages/core/src/rules/index.ts
- packages/core/test/rules/align_pseudo_comments.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
- web/rules/package-lock.json
- web/rules/package.json
closes https://github.com/abaplint/abaplint/issues/1828
quick fix: todo
> 2.108.0: new rule align_pseudo_comments

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/1_lexer/lexer_stream.ts
- packages/core/src/rules/align_pseudo_comments.ts
- packages/core/test/abap/lexer/lexer.ts
- packages/core/test/rules/align_pseudo_comments.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
- web/rules/package-lock.json
- web/rules/package.json
> 2.108.1: bugfix align_pseudo_comments

- package-lock.json
- package.json
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/objects/transaction.ts
- packages/core/src/rules/downport.ts
- packages/core/src/rules/keyword_case.ts
- packages/core/test/objects/transaction.ts
- packages/core/test/rules/downport.ts
- packages/core/test/rules/keyword_case.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
- web/rules/package-lock.json
- web/rules/package.json
> 2.108.5: bugfix keyword_case + bugfix downport + parsing TRAN

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/5_syntax/_type_utils.ts
- packages/core/src/objects/extension_index.ts
- packages/core/test/abap/syntax/syntax.ts
- packages/core/test/objects/extension_index.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
- web/rules/package-lock.json
- web/rules/package.json
> 2.108.8: bugfix type check

- package-lock.json
- package.json
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/scripts/schema.json
- packages/core/src/rules/check_subrc.ts
- packages/core/src/rules/select_single_full_key.ts
- packages/core/src/rules/unnecessary_return.ts
- packages/core/test/rules/unnecessary_return.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
- web/rules/package-lock.json
- web/rules/package.json
> 2.108.9: add optional quick fix for `select_single_full_key`

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/2_statements/expressions/type_table.ts
- packages/core/src/abap/5_syntax/basic_types.ts
- packages/core/test/abap/statements/data.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
- web/rules/package-lock.json
- web/rules/package.json
> 2.110.5: bugfix, LIKE RANGE OF

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/2_statements/expressions/sql_compare.ts
- packages/core/test/abap/statements/select.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
- web/rules/package-lock.json
- web/rules/package.json
> 2.110.6: bugfix SELECT syntax

- package-lock.json
- package.json
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/5_syntax/structures/data.ts
- packages/core/test/rules/unknown_types.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
- web/rules/package-lock.json
- web/rules/package.json
> 2.110.7: bugfix

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/scripts/schema.json
- packages/core/src/abap/5_syntax/expressions/attribute_chain.ts
- packages/core/src/abap/5_syntax/expressions/cast.ts
- packages/core/src/abap/5_syntax/expressions/component_chain.ts
- packages/core/src/abap/5_syntax/expressions/method_call_chain.ts
- packages/core/src/abap/5_syntax/structures/data.ts
- packages/core/src/abap/types/interface_definition.ts
- packages/core/src/rules/double_space.ts
- packages/core/test/rules/double_space.ts
- packages/core/test/rules/unknown_types.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
- web/rules/package-lock.json
- web/rules/package.json
> 2.112.1: adjust error positions + double_space skips

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/rules/unnecessary_pragma.ts
- packages/core/test/rules/unknown_types.ts
- packages/core/test/rules/unnecessary_pragma.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.112.3: bugfix unnecessary_pragma

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/2_statements/expressions/sql_function.ts
- packages/core/test/rules/keyword_case.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
- web/rules/package-lock.json
- web/rules/package.json
> 2.112.4: bugfix, keyword case sql functions

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/2_statements/statement_parser.ts
- packages/core/test/rules/downport.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
- web/rules/package-lock.json
- web/rules/package.json
> 2.112.6: bugfix downport

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/scripts/schema.json
- packages/core/scripts/schema.ts
- packages/core/src/abap/flow/selection_events.ts
- packages/core/src/abap/flow/statement_flow.ts
- packages/core/src/lsp/language_server.ts
- packages/core/src/rules/add_test_attributes.ts
- packages/core/src/rules/empty_event.ts
- packages/core/src/rules/implicit_start_of_selection.ts
- packages/core/src/rules/index.ts
- packages/core/test/abap/flow/statement_flow.ts
- packages/core/test/lsp/diagnostics.ts
- packages/core/test/registry.ts
- packages/core/test/rules/add_test_attributes.ts
- packages/core/test/rules/empty_event.ts
- packages/core/test/rules/implicit_start_of_selection.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
- web/rules/package-lock.json
- web/rules/package.json
* `add_test_attributes`, closes #3406
* `implicit_start_of_selection`, closes #3403
* `empty_event`, closes #2619
> 2.113.0: 3 new rules

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/lsp/_lookup.ts
- packages/core/test/lsp/diagnostics.ts
- packages/core/test/lsp/hover.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
- web/rules/package-lock.json
- web/rules/package.json
but only if there is exactly one main program
> 2.113.6: fix hover in includes, sloooow

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/rules/indentation.ts
- packages/core/test/rules/indentation.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
- web/rules/package-lock.json
- web/rules/package.json
> 2.113.15: indentation rule bugfix

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/2_statements/expressions/type_table.ts
- packages/core/src/cds/cds_determine_types.ts
- packages/core/src/cds/expressions/cds_condition.ts
- packages/core/src/cds/expressions/cds_function.ts
- packages/core/test/abap/statements/data.ts
- packages/core/test/cds/cds_parser.ts
- packages/core/test/objects/data_definition.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.113.37: additional cds functions

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/rules/downport.ts
- packages/core/test/rules/downport.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.113.80: bugfix downport

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/2_statements/statements/field.ts
- packages/core/src/abap/2_statements/statements/module.ts
- packages/core/src/pretty_printer/indent.ts
- packages/core/test/abap/structures/dynpro_logic.ts
- packages/core/test/rules/indentation.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.113.85: bugfix dynpro stuff

- README.md
changes the fix abapGit Github URL form larshp to abapGit
> fix abapGit Github URL

- package-lock.json
- package.json
- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/5_syntax/expressions/method_source.ts
- packages/core/src/cds/expressions/cds_cast.ts
- packages/core/test/cds/cds_parser.ts
- packages/core/test/rules/unused_variables.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.113.101: bugfixes

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/2_statements/expressions/string_template_formatting.ts
- packages/core/src/abap/types/method_definition.ts
- packages/core/test/abap/expressions/string_template.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
and fix syntax for [otel](https://github.com/abapify/otel)
> 2.113.108: add class name and bugfix syntax

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/cli/src/file_operations.ts
- packages/core/package-lock.json
- packages/core/package.json
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.113.123: update glob

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/rules/parser_missing_space.ts
- packages/core/test/rules/parser_missing_space.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.113.148: bugfix parser_missing_space

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/rules/downport.ts
- packages/core/test/rules/downport.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
- web/rules/package-lock.json
- web/rules/package.json
> 2.113.191: bugfix downport

- packages/core/src/rules/implement_methods.ts
- packages/core/test/rules/implement_methods.ts
> Fix false positive on implement_methods in complex inheritance setup

- .github/workflows/regression.yml
Reverts abaplint/abaplint#3719
> Revert "Change trigger to pull_request_target for regression workflow"

- packages/cli/package-lock.json
- packages/cli/package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/abap/2_statements/statements/modify_entities.ts
- packages/core/src/abap/2_statements/statements/read_entities.ts
- packages/core/src/abap/5_syntax/basic_types.ts
- packages/core/src/abap/5_syntax/statements/class_implementation.ts
- packages/core/src/cds/expressions/cds_function_input.ts
- packages/core/src/rules/align_type_expressions.ts
- packages/core/src/rules/identical_contents.ts
- packages/core/test/abap/statements/modify_entities.ts
- packages/core/test/abap/statements/read_entities.ts
- packages/core/test/rules/align_type_expressions.ts
- packages/core/test/rules/identical_contents.ts
- packages/monaco/package-lock.json
- packages/monaco/package.json
- web/playground/package-lock.json
- web/playground/package.json
> 2.113.220: bugfix `align_type_expressions` + bugfix `identical_contents`
