abaplint/abaplint

- src/formatters/junit.ts
- src/registry.ts
also changed the xml build from string concatination to use xml-js (already included as dependency) js-object to xml output.
Example output merge request:
https://gitlab.com/sbu-absw/abaplint-example/merge_requests/3
> Junit gitlab improvements

- src/abap/pretty_printer.ts
- test/abap/pretty_printer.ts
to #337 fix class implementation indent
P.S. indentation code became less readable. I'd propose making the run non-static and split into 2 methods (well, the original one and the "fix" for class indentation). Can add a commit if OK.
> class implementation indent fix

- .gitignore
- .vscode/launch.json
Adds integration with the vscode debugger. As opposed to `npm run test`, this will stop at breakpoints in your code.
- The timeout is in miliseconds. 2 minutes should be more than enough as the tests run in <10 seconds on my machine.
> Add launch config for debugging tests

- src/config.ts
- src/rules/_basic_rule_config.ts
- test/config.ts
If the rule is present in the config, it has `enabled: true` by default.
See https://github.com/abaplint/abaplint/pull/525 for reasoning.
> Specified rules have enabled = true by default

- test/rules/class_attribute_names.ts
- test/rules/constructor_visibility_public.ts
- test/rules/definitions_top.ts
- test/rules/empty_line_in_statement.ts
- test/rules/exit_or_check.ts
- test/rules/functional_writing.ts
- test/rules/if_in_if.ts
- test/rules/keywords_upper.ts
- test/rules/local_variable_names.ts
- test/rules/method_length.ts
- test/rules/method_parameter_names.ts
- test/rules/mix_returning.ts
- test/rules/remove_descriptions.ts
- test/rules/rfc_error_handling.ts
- test/rules/syntax/begin_end_names.ts
- test/rules/syntax/check_transformation_exists.ts
- test/rules/syntax/implement_methods.ts
- test/rules/syntax/superclass_final.ts
- test/rules/unreachable_code.ts
This PR replaces concatenation using `\n" +` with multiline strings in test data to improve readability.
I think aligning like this 
```
const abap = `
string`;
```
adds a newline to the beginning of the string, but it is the most readable form and doesn't matter to the parser.
> Use multiline strings in tests

- .github/workflows/nodejs.yml
... otherwise contributors are constantly receiving build failed notifications
> deploy schema only from the root repo

- src/rules/_basic_rule_config.ts
Makes the config even more self-documenting: allows user-defined reasons for why the rules are there in the first place. You can link to clean abap, some in-house rules or just have a short description. It is also useful to put a comment if you're disabling a rule temporarily.
> Add reason attribute to rule config

- web/playground/src/widgets/help.ts
Currently they do this:
I don't think anyone would want to leave their work to go look at a diagram. This makes the links open in a new tab.
> Playground - open links to syntax diagrams in new tab

- travis.sh
- web/playground/package-lock.json
- web/playground/package.json
- web/playground/public/index.html
- web/playground/src/custom.d.ts
- web/playground/src/index.less
- web/playground/src/index.ts
- web/playground/src/widgets/welcome.ts
- web/playground/webpack.config.js
portion 2
- index.html, as well as favicons and other public images are now built right into `build` dir (easier to copy, `serve build` works, bundle names added to the html automatically and kind of consistent in general)
- small images are inlined (url-loader for files < 1k)
- just 4 bundle.js files (though for production it might be not optimal ... maybe ... seems like monaco will be a heavy file anyway)
- added less processor for css (can change to sass if any preference ...)
> more playground webpack env improvements

- src/abap/types/class_attributes.ts
- src/rules/no_public_attributes.ts
- test/rules/no_public_attributes.ts
- adds config to allow public READ-ONLY attributes
- completely refactored the logic... I may have gone too far in a few places there, let me know if I should simplify it a bit (i.e. keep it all in the runParsed function)
- adds some helper functions for class_atributes 
- adds unit tests
- closes #345
> Rule: No Public Attributes, Refactoring + READ-ONLY

- src/rules/method_length.ts
- test/rules/method_length.ts
- add option to ignore test classes for method length checks
- if enabled, ignores  `.testclasses.` files
- add new test cases
- closes #631
> Method Length: Option to ignore Test Classes

- scripts/schema.json
- scripts/schema.ts
- src/pretty_printer/fix_keyword_case.ts
- src/pretty_printer/pretty_printer.ts
- src/rules/index.ts
- src/rules/keyword_case.ts
- test/abap/pretty_printer.ts
- test/rules/_utils.ts
- test/rules/keyword_case.ts
@sbcgua you should like this
- `keywords_upper` renamed to `keyword_case` which has a `style: upper | lower` property
- pretty printer will uppercase or lowercase depending on the style
> Configurable keyword case + pretty printer

- scripts/schema.json
- scripts/schema.ts
- src/rules/index.ts
- src/rules/whitespace/newline_between_methods.ts
- test/rules/whitespace/newline_between_methods.ts
- checks for a single new line after each `ENDMETHOD`
- exception: `ENDMETHOD` before `ENDCLASS`, newline optional in this case (multiple newlines will be marked though)
- closes #164
> New Rule: Newline between methods

- scripts/schema.json
- scripts/schema.ts
- src/rules/check_comments.ts
- src/rules/index.ts
- test/rules/check_comments.ts
- initially only check for end-of-line comments (part of #633)
(approach may be a bit "hacky", might be solved with a regex instead?)
> New Rule: Comment Checks

- scripts/schema.json
- src/rules/naming/local_class_naming.ts
- test/rules/naming/local_class_naming.ts
- Added option `exception` to rule `local_class_naming` (resolves #400)
- refactored the rule logic to use newer constructs (makes it more readable)
> Local Class Naming: Add option for Exception classes + Refactoring

- src/lsp/index.ts
- src/pretty_printer/remove_sequential_blanks.ts
- test/abap/pretty_printer.ts
- Remove trailing (and leading) whitespace with a simple trim (tries to resolve #564)
- The effect in the playground is that no new lines are added - but the trailing whitespace is NOT removed. The cause could lie within mono/language server itself?
> Pretty Printer: Trailing whitespace

- scripts/schema.json
- scripts/schema.ts
- src/rules/fully_type_constants.ts
- src/rules/index.ts
- test/registry.ts
- test/rules/fully_type_constants.ts
- Checks for implicit typing of Constants (and data definitions, if option enabled), first part of #540
> New Rule: Fully type Constants (and data definitions)

- scripts/schema.json
- scripts/schema.ts
- src/rules/index.ts
- src/rules/naming/selection_screen_naming.ts
- test/rules/naming/selection_screen_naming.ts
- New rule for selection-screen variables (parameters, select-options, resolves #358)
- default pattern for parameters = `^P_.+$`
- default pattern for select-options = `^S_.+$`
> New Rule: Selection-Screen variable naming 

- src/rules/prefix_is_current_class.ts
- src/rules/whitespace/newline_between_methods.ts
- closes #710
- also fixes trailing whitespace for linter
> newline_between_methods: clarify description

- scripts/schema.json
- src/abap/nodes/statement_node.ts
- src/rules/prefix_is_current_class.ts
- test/rules/prefix_is_current_class.ts
- adds unit tests
- adds option `omitMeInstanceCalls` to check `me->` usage in instance method calls (suggestions for a better name for the option are welcome)
- adds another concatTokens method that excludes Strings and Comments (name is also debatable)
closes #721
> PrefixIsCurrentClass:  Add option, tests and refactoring

- src/abap/nodes/statement_node.ts
- src/rules/prefix_is_current_class.ts
- report issues at relevant position instead of statement (fixes #727)
- changed description to `Reference to current class can be omitted: <classname>`
- add helper function to find a token-sequence (for now only two tokens by text)
> prefix_is_current_class: issue at position instead of statement

- scripts/schema.json
- src/config.ts
- src/pretty_printer/remove_sequential_blanks.ts
- src/rules/_basic_rule_config.ts
- test/config.ts
This removes the enabled property from each rule's config. All mentioned rules will be enabled, with the exception of the `"rule": false` syntax, which I think still makes sense if there has to be a `true` option.
Resolves #726
> Remove enabled property from rules

- src/rules/unused_variables.ts
Resolves #750.
For some reason this was specified here as well instead of the basic config. Removing the attribute does not change the schema. I think it never worked with the schema in the first place, which is why the warning is there.
> Remove duplicate 'enabled' from unused_variables

- src/rules/commented_code.ts
- test/rules/commented_code.ts
- added check for inline comments (abapdoc comments excluded)
- refactored some variable names
- added additional test cases
- changed logic:
- currently: if the comment block contains a single line that is not a statement, it will NOT be reported (see #751, the "todo"-line)
- new: if the block contains at least a single statement, the block will be reported
- resolves #751
> Commented Code: Fixes + Refactoring

- src/abap/expressions/inline_field_definition.ts
- src/abap/expressions/source.ts
- test/abap/statements/move.ts
- closes #747
Note: Currently, the `InlineFieldDefinition` works similar to a data definition, even though the variable should only be available in the scope of the move operation. Create a new issue for this?
Example:
```abap
DATA(foo) = REDUCE i( INIT s TYPE i FOR i = 1 UNTIL i > 10 NEXT s = s + i ).
" should give an error
s = 2.
```
> check_syntax bugfix

- src/rules/naming/class_attribute_names.ts
- src/rules/naming/local_class_naming.ts
- src/rules/naming/local_variable_names.ts
- src/rules/naming/method_parameter_names.ts
- src/rules/naming/object_naming.ts
- test/rules/naming/class_attribute_names.ts
- test/rules/naming/local_class_naming.ts
- test/rules/naming/local_variable_names.ts
fixes #776 
the check and set to default is during "runtime" because the `patternKind` is not necessarily set with the setter-method. Not nice but should be a temporary workaround
> Naming Rules: Patternkind to "Required" when "undefined"

- package.json
For now all scripts in the root package
creates global links for core and monaco
adds links into packages
resolves #834
> Scripts for npm links

- packages/core/src/rules/naming/local_variable_names.ts
- packages/core/test/rules/naming/local_variable_names.ts
resolves #868 
logic changed for data-begin: only check data structures with depth 1 (in relation to method/form etc)
> local_variable_names: change logic for data-begin structures, check only first level

- packages/core/src/index.ts
Looks like this will work for abappretty:
```typescript
import { PrettyPrinter } from "@abaplint/core/build/src/pretty_printer/pretty_printer"
```
but relies too much on internal structure
> expose pretty printer

- packages/core/src/objects/_abap_object.ts
- packages/core/test/get_abap.ts
Not that useful, but I find it cleaner.
This would have worked fine for the main class, but the symbol based one works for subclasses too
```typescript
public static is(x:any):x is ABAPObject{
return o instanceof ABAPObject;
}
```
PS: this also worked fine, but leaving an unused error for [tag]. Lines 25 and 26 was added to make linters happy
```typescript
public static is(x:any):x is ABAPObject{
return !!x?.[tag];
}
```
Could also have done this, but ignores any type error on that line, not only the unused variable one, but ignores any TS error for that line:
```typescript
// @ts-ignore
private [tag] = true;
public static is(x:any):x is ABAPObject{
return !!x?.[tag];
}
```
> ABAPObject type guard

- packages/core/src/rules/whitespace/double_space.ts
- packages/core/test/rules/whitespace/double_space.ts
change reporting from token to specific position
also:
- remove workarounds as referenced issue is closed
- add check for empty space between parentheses, one reporting
closes #820, closes #735, closes #705
Now:
With these changes:
> Double space: Change reported position

- packages/core/src/rules/preferred_compare_operator.ts
- packages/core/test/rules/preferred_compare_operator.ts
Problem: user can enter `badOperators` freely - how to specify the operators that are replacements?
Currently only two letter operators and `><` are quick fixable.
What if user puts in contradictory operators, e.g. `EQ` and `=`?
> preferred_compare_operator: quick fix

- packages/core/src/rules/begin_end_names.ts
- packages/core/test/rules/begin_end_names.ts
change `END OF` identifier to be the same as in `BEGIN OF`
> begin_end_names: add quick fix

- packages/core/scripts/schema.json
- packages/core/src/rules/sequential_blank.ts
- packages/core/test/rules/sequential_blank.ts
closes #967 
This was more annoying than expected, please also note the last two test cases. 
For some reason it does not remove a single newline when run in the test, but in the playground it works properly. Maybe this is due to how the lines are split on `\n`?
> sequential_blank: add quick fix

- packages/core/src/abap/2_statements/statements/export.ts
- packages/core/src/abap/2_statements/statements/import.ts
- packages/core/test/abap/statements/export.ts
- packages/core/test/abap/statements/import.ts
- packages/core/test/abap/syntax/syntax.ts
Fixes detection of cluster tables for EXPORT/IMPORT statements (DELETE FROM DATABASE works with cluster tables and served as a template).
Reproduce:
CONSTANTS gc_test TYPE c LENGTH 10 VALUE 'TEST'.
DATA gt_data TYPE TABLE OF string.
" works:
DELETE FROM DATABASE indx(zr) ID gc_test.
" "indx" not found(check_syntax):
EXPORT data = gt_data TO DATABASE indx(zr) ID gc_test.
" "indx" not found(check_syntax):
IMPORT data = gt_data FROM DATABASE indx(zr) ID gc_test.
I added a couple tests although there were already some similar ones.
> Update EXPORT/IMPORT DATABASE to recognize db table

- packages/core/src/abap/2_statements/expressions/form_param_type.ts
- packages/core/test/abap/statements/form.ts
Closes https://github.com/abaplint/abaplint/issues/1021
Quick fix but it seems that FormParamType could be replaced by expression/Type:
https://help.sap.com/doc/abapdocu_754_index_htm/7.54/en-US/abapform_parameters.htm
> Add LINE OF/REF TO for form parameters

- packages/core/package.json
- packages/core/src/rules/keyword_case.ts
- packages/core/test/rules/_utils.ts
- packages/core/test/rules/keyword_case.ts
Adds `ignoreGlobalClassBoundaries` flag for `keyword_case` rule.
Case: keyword style set to lower_case
```abap
CLASS zcl_my DEFINITION FINAL PUBLIC.
public section.
methods x.
ENDCLASS.
CLASS zcl_my IMPLEMENTATION.
method x. endmethod.
ENDCLASS.
```
The class/endclass statements are uppercased by SE80. Even if pretty print settings are set to lowercase. So should be a possiblity to ignore it.
while this should be caught properly
```abap
CLASS zcl_my DEFINITION FINAL PUBLIC.
public section.
METHODS x. " <<<<<<
ENDCLASS.
```
On the way:
- added `test:only` npm script
- added `only` flag to `testRule` util to temporary focus on specific test cases
P.S. sorry for some emotions, but am I the only one who find the current test flows inconvenient ? Or I just don't know the right way ? :))) does …
> Keyword rule ignore class boundary

- packages/core/src/rules/keyword_case.ts
- packages/core/test/rules/keyword_case.ts
```abap
INTERFACE zif_my PUBLIC.
methods x.
ENDINTERFACE.
```
should pass
style = lower
Fix from previous contribution, completely forgot about interfaces :(
> keyword_case ignoreGlobalClassBoundaries for interfaces

- packages/core/scripts/schema.json
- packages/core/scripts/schema.ts
- packages/core/src/rules/call_transaction_authority_check.ts
- packages/core/src/rules/check_abstract.ts
- packages/core/src/rules/index.ts
- packages/core/src/rules/obsolete_statement.ts
- packages/core/test/rules/call_transaction_authority_check.ts
- packages/core/test/rules/check_abstract.ts
- Add new rule: call transaction, authority check (closes #1310 )
- Allow abstract and final for test classes (closes #1392 )
- Fix typo in `obsolete_statements`: `FIELD-SYMBOLS` instead of `FIELD-SYMBOL`
> New Rule: Call Transaction, Authority Check; Allow Abstract Final in Test Classes

- README.md
- package-lock.json
- package.json
This makes tests discoverable/runnable from the repository root by the test explorer extension.
Note that this is rather limited as you need to rebuild the whole thing on change, also navigation to each test only works if you are in the subfolder.
> Fix test discovery for root folder

- packages/core/src/rules/parser_702_chaining.ts
- packages/core/test/rules/parser_702_chaining.ts
ref #1399
The following case (from the referenced issue) is currently not reported:
add additional test case, check for `EXCEPTIONS` keyword
> MethodChain 702, Add missing case

- packages/core/scripts/schema.json
- packages/core/src/_config.ts
- packages/core/src/version.ts
Resolves #1562 .
There are some whitespace inconsistencies when I run the schema script. I will undo them, but I'd like to know the cause - I did a fresh clone just to be sure and they still appear.
> Make language version optional in config, up default to 755

- packages/core/src/rules/exit_or_check.ts
- packages/core/test/rules/exit_or_check.ts
Default value for allow* should be false => exit or check is not allowed outside loop => error.
Value when checking should be false => it is not allowed, we will display error.
> exit_or_check - fix confusion with rule config

- packages/core/src/rules/exit_or_check.ts
- packages/core/test/rules/exit_or_check.ts
The fix for CHECK adds NOT because it is easier than figuring out the correct operator + another check is handling that.
> exit_or_check quickfix

- packages/core/src/rules/in_statement_indentation.ts
- packages/core/test/rules/in_statement_indentation.ts
- Add option to specify additional indent for block statements (set to 0 if you don't want this)
- Extend description and examples
- Add CASE to block statements (probably rare that it spans multiple lines)
> Enhance in_statement_indentation

- packages/core/src/rules/obsolete_statement.ts
- packages/core/src/version.ts
- packages/core/test/rules/obsolete_statement.ts
- packages/core/test/version.ts
Ref #2132.
Posix regex becomes obsolete in abap version 7.56, however this versions is not yet available to the public.
Should I add new abap version 7.56 for this?
Regex in string function is not in this as I don't know how to easily check built-in methods (and I don't have the full list of methods that use this). Generic parameter name "regex" would create false positives for user defined methods.
> obsolete_statements - posix regex

- packages/core/scripts/schema.json
- packages/core/src/rules/constant_classes.ts
- packages/core/test/rules/constant_classes.ts
- fixes issue with case when comparing types
- fixes [Object object] in message
- because sometimes we have an additional constant in our pattern, the check always reported it as extra. Added option to have another constant containing the domain name which also be be validated (name, value).
So if specified, this requires an additional constant
```CONSTANTS {name_from_config} TYPE domname VALUE `THE_DOMAIN_NAME`.```
> constant_classes - Corrections, add option to have constant with domain name

- packages/core/src/rules/no_chained_assignment.ts
See this:
```abap
REPORT ZTEST.
DATA v1 TYPE c LENGTH 5.
DATA v2 TYPE c LENGTH 2.
DATA v3 TYPE c LENGTH 5 VALUE 'ABCDE'.
v1 = v2 = v3.
WRITE v1. " AB
v2 = v3.
v1 = v3.
WRITE v1.  " ABCDE
```
> no_chained_assignments example

- packages/core/src/version.ts
ABAP 7.56 is already available to all customers:
https://help.sap.com/doc/abapdocu_latest_index_htm/latest/en-US/abennews-756.htm
> Bump up ABAP version to 7.56

- packages/core/scripts/schema.json
- packages/core/src/rules/no_public_attributes.ts
The rule is OK, but should be exemptable for test classes. Public attributes simplify test code e.g. for spy pattern in test doubles. (Personally I think `true` should even be default).
> Rule no_public_attributes can ignore test classes

- packages/core/src/abap/2_statements/expressions/type_table.ts
- packages/core/test/abap/statements/type.ts
Fix so first statement is syntax error:
```abap
DATA itab1 TYPE STANDARD TABLE string. "<<< should error
DATA itab2 TYPE STANDARD TABLE OF string.
```
Ref https://github.com/abaplint/abaplint/issues/2907
> Fix "TABLE OF" for table types

- packages/cli/src/cli.ts
- packages/cli/src/index.ts
Sometimes, we would like to trigger abaplint cli for a single file or folder (glob). Therefore, I would like to propose a new cli arg to replace the global files defined in the `abaplint.json`, if it is used.
For instance:
`abaplint --file package/*.abap`
`abaplint --file package/person.clas.abap`
> feat: File Argument

- packages/core/src/rules/no_prefixes.ts
Cover more cases by default like 
- `MV_...` for instance variables 
- `C_...` for constants
- `ST_...` for statics
Switch to upper-case to align with other rule definitions.
> no_prefixes: expand defaults

- packages/core/src/rules/fully_type_itabs.ts
- packages/core/test/rules/fully_type_itabs.ts
Dev team reported false negatives for internal tables defined through a type variable.
> Run fully_type_itabs on DATA and TYPES statements.

- packages/core/src/abap/flow/flow_graph.ts
In this PR, I'm removing the listInto method inside the FlowGraph and hasEdges was made private since that is the only file that was using it.
> Remove the listInto method and make hasEdges private

- packages/core/src/abap/5_syntax/statements/free.ts
- packages/core/src/abap/5_syntax/statements/refresh.ts
- packages/core/src/abap/5_syntax/syntax.ts
- packages/core/test/rules/unused_variables.ts
Backstory: quick fixes of unused_variables where the variables were only used in a FREE or REFRESH statement would delete the variable and result in syntax errors not detected by abaplint.
> Implement FREE and REFRESH statements
